IF OBJECT_ID('ENE_ENTIDAD_EDUCATIVA', 'U') > 0
BEGIN
	DROP TABLE ENE_ENTIDAD_EDUCATIVA;
END

CREATE TABLE ENE_ENTIDAD_EDUCATIVA (
	ENE_ID uniqueidentifier PRIMARY KEY,
	ENE_NIT VARCHAR(16) NOT NULL,
	ENE_NOMBRE_RAZON_SOCIAL VARCHAR(100) NOT NULL,
	ENE_ESTADO BIT NOT NULL,
	ENE_CREATEDOPOR uniqueidentifier NOT NULL,
	ENE_FECHACREACION DATETIME NOT NULL,
	ENE_MODIFICADOPOR uniqueidentifier NULL,
	ENE_FECHAMODIFICACION DATETIME NULL
);