/*
Nombre: DEPARTAMENTO
Descripcion: Tabla departamento
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/


IF OBJECT_ID('GA2.dbo.DPD_DEPARTAMENTO') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.DPD_DEPARTAMENTO;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.DPD_DEPARTAMENTO (
	DPD_ID int NOT NULL,
	DPP_ID int NOT NULL,
	DPD_CODIGO int NOT NULL,
	DPD_NOMBRE varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	REG_ID int NOT NULL,
	CONSTRAINT PK_DPD_DEPARTAMENTO PRIMARY KEY (DPD_ID),
	CONSTRAINT FK_DPD_DEPARTAMENTO_DPP_PAIS FOREIGN KEY (DPP_ID) REFERENCES GA2.dbo.DPP_PAIS(DPP_ID)
);
END