/*
Nombre: ObtenerCiudades
Descripcion: Obteniene ciudades que existen
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/


IF OBJECT_ID('GA2.dbo.DPC_CIUDAD') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.DPC_CIUDAD;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.DPC_CIUDAD (
	DPC_ID int NOT NULL,
	DPD_ID int NOT NULL,
	DPC_CODIGO int NOT NULL,
	DPC_NOMBRE varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_DPC_CIUDAD PRIMARY KEY (DPC_ID),
	CONSTRAINT FK_DPC_CIUDAD_DPD_DEPARTAMENTO FOREIGN KEY (DPD_ID) REFERENCES GA2.dbo.DPD_DEPARTAMENTO(DPD_ID)
);
END