IF OBJECT_ID('PRN_PROGRAMA_NIVEL', 'U') > 0
BEGIN
	DROP TABLE PRN_PROGRAMA_NIVEL;
END

CREATE TABLE PRN_PROGRAMA_NIVEL (
	PRN_ID uniqueidentifier PRIMARY KEY,
	PGN_ID_FK uniqueidentifier FOREIGN KEY REFERENCES PGN_PROGRAMA_ENTIDAD (PGN_ID),
	NVE_ID_FK uniqueidentifier FOREIGN KEY REFERENCES NVE_NIVEL_EDUCATIVO (NVE_ID),
	PRN_ESTADO BIT NOT NULL,
	PRN_CREATEDOPOR uniqueidentifier NOT NULL,
	PRN_FECHACREACION DATETIME NOT NULL,
	PRN_MODIFICADOPOR uniqueidentifier NULL,
	PRN_FECHAMODIFICACION DATETIME NULL
);