IF OBJECT_ID('PGN_PROGRAMA_ENTIDAD', 'U') > 0
BEGIN
	DROP TABLE PGN_PROGRAMA_ENTIDAD;
END

CREATE TABLE PGN_PROGRAMA_ENTIDAD (
	PGN_ID uniqueidentifier PRIMARY KEY,
	PGE_ID_FK uniqueidentifier FOREIGN KEY REFERENCES PGE_PROGRAMA_EDUCATIVO (PGE_ID),
	ENE_ID_FK uniqueidentifier FOREIGN KEY REFERENCES ENE_ENTIDAD_EDUCATIVA (ENE_ID),
	PGN_ESTADO BIT NOT NULL,
	PGN_CREATEDOPOR uniqueidentifier NOT NULL,
	PGN_FECHACREACION DATETIME NOT NULL,
	PGN_MODIFICADOPOR uniqueidentifier NULL,
	PGN_FECHAMODIFICACION DATETIME NULL
);