/*
Nombre: TIPO_CREDITO 
Descripcion: Tabla TIPO_CREDITO 
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/

IF OBJECT_ID('GA2.dbo.TCR_TIPO_CREDITO') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.TCR_TIPO_CREDITO;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.TCR_TIPO_CREDITO (
	TCR_ID int IDENTITY(1,1) NOT NULL,
	TCR_DESCRIPCION varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	TCR_ID_PADRE int NOT NULL,
	TCR_NIVEL int NOT NULL,
	TCR_ESTADO int NOT NULL,
	TCR_CREADO_POR uniqueidentifier NOT NULL,
	TCR_FECHA_CREACION datetime NOT NULL,
	TCR_MODIFICADO_POR uniqueidentifier NULL,
	TCR_FECHA_MODIFICACION datetime NULL,
	CONSTRAINT PK_TCR_TIPO_CREDITO PRIMARY KEY (TCR_ID)
);
END