IF OBJECT_ID('NVE_NIVEL_EDUCATIVO', 'U') > 0
BEGIN
	DROP TABLE NVE_NIVEL_EDUCATIVO;
END

CREATE TABLE NVE_NIVEL_EDUCATIVO (
	NVE_ID uniqueidentifier PRIMARY KEY,
	NVE_DESCRIPCION VARCHAR(50),
	NVE_ESTADO BIT NOT NULL,
	NVE_CREATEDOPOR uniqueidentifier NOT NULL,
	NVE_FECHACREACION DATETIME NOT NULL,
	NVE_MODIFICADOPOR uniqueidentifier NULL,
	NVE_FECHAMODIFICACION DATETIME NULL
);