-----------------------------------------
--- Author Oscar Julian Rojas
--- Descripcion Talba SubMenu de aplicacion
--- Date 28-04-2021
------------------------------------------
CREATE TABLE GA2.dbo.SBM_SUBMENU (
	SBM_ID UNIQUEIDENTIFIER PRIMARY KEY, 
	MNU_ID UNIQUEIDENTIFIER NOT NULL,
	SBM_DESCRIPCION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SBM_LINK varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SBM_ICONO varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SBM_VISIBLE BIT NULL,
	FRM_ID UNIQUEIDENTIFIER NULL,
	SBM_MODIFICADOPOR UNIQUEIDENTIFIER NULL,
	SBM_FECHAMODIFICACION DATETIME,
	SBM_CREADOPOR UNIQUEIDENTIFIER NOT NULL,
	SBM_FECHACREACION DATETIME NOT NULL,
	SBM_ESTADO BIT NULL
) GO;

 
      