
CREATE TABLE GA2.dbo.USR_USERS (
	USR_ID uniqueidentifier Default newId() NOT NULL,
	USR_NOMBRE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	USR_SEGUNDONOMBRE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
	USR_APELLIDO nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	USR_SEGUNDOAPELLIDO nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	USR_USERNAME nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	USR_PASSWORD nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	USR_IDENTIFICACION nvarchar(16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	TID_ID uniqueidentifier NOT NULL,
	USR_EMAIL nvarchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ROLID uniqueidentifier NOT NULL,
	USR_MODIFICADOPOR uniqueidentifier NULL,
	USR_FECHAMODIFICACION datetime NULL,
	USR_CREADOPOR uniqueidentifier NOT NULL,
	USR_FECHACREACION datetime NOT NULL,
	USR_ESTADO bit NOT NULL);