IF OBJECT_ID('ObtenerClienteInformacion', 'P') > 0
BEGIN
	DROP PROCEDURE ObtenerClienteInformacion
END
GO
CREATE PROCEDURE ObtenerClienteInformacion
	@IdCliente					int
AS 
BEGIN
	SELECT CLI_ID, TPA_ID, TID_ID, CLI_IDENTIFICACION, CLI_FECHA_EXPEDICION, DPD_ID_IDENTIFICACION_EXPEDIDA, DPC_ID_IDENTIFICACION_EXPEDIDA,
		CLI_LUGAR_EXPEDICION, CLI_CODIGO_MILITAR, CLI_PRIMER_NOMBRE, CLI_SEGUNDO_NOMBRE, CLI_PRIMER_APELLIDO, CLI_SEGUNDO_APELLIDO,
		CLI_FECHA_NACIMIENTO, DPP_ID_PAIS_NACIMIENTO, DPD_ID, DPC_ID, CLI_LUGAR_NACIMIENTO, CAT_SEXO, CAT_ESTADO_CIVIL, CLI_PROFESION,
		CLI_UNIDAD, CTG_ID, FRZ_ID ,GRD_ID, UEJ_ID, CLI_FECHA_INSCRIPCION, CLI_FECHA_ALTA, CLI_REGIMEN, CTS_SLP, CLI_FECHA_REINTEGRO,
		ECL_ID, CLI_VALIDACION, CLI_ID_PATROCINADOR, CLI_PARTICIPACION, CLI_RESOLUCION, CLI_VALIDACION_BIOMETRICA, ECL_ID_AVAL,
		CLI_INTEGRACION_GA2, CLI_ACTIVO, CLI_INTEGRACION_GA2_PAYLOAD
	FROM CLI_CLIENTE
	WHERE CLI_ID = @IdCliente
END


