/*
Nombre: ActualizarLegalTasa
Descripcion: Actualiza el legal tasa
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/
CREATE PROCEDURE[dbo].ActualizarLegalTasa
@ID int,
@TASAFRECH float,
@VIGENCIATASAFRECH datetime,
@FECHAMODIFICACION datetime,
@MODIFICADOPOR int,
@ESTADO bit
AS 
BEGIN
UPDATE GA2..PARAM_LEGAL_TASA
SET LEG_T_TASA_FRECH = @TASAFRECH,
LEG_T_VIGENCIA_TASA_FRECH = @VIGENCIATASAFRECH,
LEG_T_FECHA_MODIFICACION = @FECHAMODIFICACION,
LEG_T_MODIFICADO_POR = @MODIFICADOPOR,
LEG_T_ESTADO = @ESTADO
WHERE LEG_T_ID = @ID
END
