/*
Nombre: CrearLiquidacion
Descripcion: Crea la Liquidacion
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/
CREATE PROCEDURE[dbo].CrearLiquidacion
@ID int,
@FECHACORTE float,
@FECHAPAGO float,
@FECHAMODIFICACION datetime,
@MODIFICADOPOR int,
@ESTADO bit
AS
BEGIN
INSERT INTO GA2..PARAM_LIQUIDACION(
LIQ_FECHA_CORTE,
LIQ_FECHA_PAGO,
LIQ_FECHA_MODIFICACION,
LIQ_MODIFICADO_POR,
LIQ_ESTADO) 
VALUES(@FECHACORTE,
@FECHAPAGO,
@FECHAMODIFICACION,
@MODIFICADOPOR,
@ESTADO)
SELECT LIQ_ID,
LIQ_FECHA_CORTE,
LIQ_FECHA_PAGO,
LIQ_FECHA_MODIFICACION,
LIQ_MODIFICADO_POR,
LIQ_ESTADO
FROM GA2..PARAM_LIQUIDACION
WHERE LIQ_FECHA_MODIFICACION =
(SELECT MAX(LIQ_FECHA_MODIFICACION) 
FROM GA2..PARAM_LIQUIDACION WHERE LIQ_ESTADO = 1)
UPDATE GA2..PARAM_LIQUIDACION 
SET LIQ_ESTADO = 0
WHERE LIQ_ID = @ID
END
