/*
Nombre: CrearPlazo
Descripcion: Crea el plazo
Elaboro: Camilo Andres Yaya poveda
Fecha: Mayo 7 de 2021
*/
CREATE PROCEDURE[dbo].CrearPlazo
@ID int,
@YEARMIN float,
@MONTHMIN float,
@YEARMAX float,
@MONTHMAX float,
@FECHAMODIFICACION datetime,
@MODIFICADOPOR int,
@ESTADO bit
AS 
BEGIN
INSERT INTO GA2..PARAM_PLAZOS(
PLAZ_YEAR_MIN,
PLAZ_MONTH_MIN,
PLAZ_YEAR_MAX,
PLAZ_MONTH_MAX,
PLAZ_FECHA_MODIFICACION,
PLAZ_MODIFICADO_POR,
PLAZ_ESTADO) 
VALUES(@YEARMIN,
@MONTHMIN,
@YEARMAX,
@MONTHMAX,
@FECHAMODIFICACION,
@MODIFICADOPOR,
@ESTADO)
SELECT PLAZ_ID,
PLAZ_YEAR_MIN,
PLAZ_MONTH_MIN,
PLAZ_YEAR_MAX,
PLAZ_MONTH_MAX,
PLAZ_FECHA_MODIFICACION,
PLAZ_MODIFICADO_POR,
PLAZ_ESTADO
FROM GA2..PARAM_PLAZOS
WHERE PLAZ_FECHA_MODIFICACION =
(SELECT MAX(PLAZ_FECHA_MODIFICACION) 
FROM GA2..PARAM_PLAZOS WHERE PLAZ_ESTADO = 1)
UPDATE GA2..PARAM_PLAZOS 
SET PLAZ_ESTADO = 0
WHERE PLAZ_ID = @ID
END