/*
Nombre: CrearSeguro
Descripcion: Crea el seguro
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/
CREATE PROCEDURE[dbo].CrearSeguro
@ID int,
@VIDA numeric,
@TODO_RIESGO numeric,
@FECHAMODIFICACION datetime,
@MODIFICADOPOR int,
@ESTADO bit
AS 
BEGIN
INSERT INTO GA2..PARAM_SEGURO
(SEG_VIDA,
SEG_TODO_RIESGO,
SEG_FECHA_MODIFICACION,
SEG_MODIFICADO_POR,
SEG_ESTADO) 
VALUES(@VIDA,
@TODO_RIESGO,
@FECHAMODIFICACION,
@MODIFICADOPOR,
@ESTADO)
SELECT SEG_ID,
SEG_VIDA,
SEG_TODO_RIESGO,
SEG_FECHA_MODIFICACION,
SEG_MODIFICADO_POR,
SEG_ESTADO
FROM GA2..PARAM_SEGURO
WHERE SEG_FECHA_MODIFICACION =
(SELECT MAX(SEG_FECHA_MODIFICACION) 
FROM GA2..PARAM_SEGURO WHERE SEG_ESTADO = 1)
UPDATE GA2..PARAM_SEGURO 
SET SEG_ESTADO = 0
WHERE SEG_ID = @ID
END