/*
Nombre: ObtenerLegalAlivio
Descripcion: Obteniene el Legal Alivio
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/
CREATE PROC[dbo].ObtenerLegalAlivio
AS 
	SELECT LEG_A_ID,
	LEG_A_ALIVIO_CUOTA,
	LEG_A_VIGENCIA_ALIVIO_CUOTA,
	LEG_A_FECHA_MODIFICACION,
	LEG_A_MODIFICADO_POR,
	LEG_A_ESTADO
	FROM GA2..PARAM_LEGAL_ALIVIO
	WHERE LEG_A_FECHA_MODIFICACION =
	(SELECT MAX(LEG_A_FECHA_MODIFICACION) 
	FROM GA2..PARAM_LEGAL_ALIVIO WHERE LEG_A_ESTADO = 1)