/*
Nombre: ObtenerLegalGmf
Descripcion: Obtiene el Legal Gmf
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/
CREATE PROC[dbo].ObtenerLegalGmf
AS 
	SELECT LEG_G_ID,
	LEG_G_GMF,
	LEG_G_VIGENCIA_GMF,
	LEG_G_FECHA_MODIFICACION,
	LEG_G_MODIFICADO_POR,
	LEG_G_ESTADO
	FROM GA2..PARAM_LEGAL_GMF
	WHERE LEG_G_FECHA_MODIFICACION =
	(SELECT MAX(LEG_G_FECHA_MODIFICACION) 
	FROM GA2..PARAM_LEGAL_GMF WHERE LEG_G_ESTADO = 1)