------------------------------------------
-- auhtor Camilo Andres Yaya Poveda
-- descripcion: Tabla para los productos
-- date: 07 / 05 / 2021
------------------------------------------
IF OBJECT_ID('GA2.dbo.PARAM_CARGUE_NOMINA') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.PARAM_CARGUE_NOMINA;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.PARAM_CARGUE_NOMINA (
	PARAM_ARCHIVO_CARGUE_NOMINA_ID int IDENTITY(1,1) NOT NULL,
	NOM_ARCHIVO_LEN int NOT NULL,
	NOM_TIPO_ARCHIVO_REPORTADO_LEN int NOT NULL,
	NOM_CLASIF_ARCHIVO_LEN int NOT NULL,
	NOM_PERIODO_APORTES_LEN int NOT NULL,
	NOM_COD_UNID_EJECUTORA_LEN int NOT NULL,
	NOM_FECHA_ENVIO_LEN int NOT NULL,
	NOM_EXTENSION_PERMITIDA varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	NOM_EXTENSION_LEN int NOT NULL,
	ENC_LEN int NOT NULL,
	ENC_CONSEC_LEN int NOT NULL,
	ENC_TIPO_ARCHIVO_LEN int NOT NULL,
	ENC_NOMB_NOMINA_UNI_EJECUTORA_LEN int NOT NULL,
	ENC_COD_UNI_EJECUTORA_LEN int NOT NULL,
	ENC_PERIODO_APORTES_LEN int NOT NULL,
	CUER_LEN int NOT NULL,
	CUER_CONSEC_LEN int NOT NULL,
	CUER_DIGITO_FUERZA_LEN int NOT NULL,
	CUER_UNI_EJECUTORA_LEN int NOT NULL,
	CUER_TIPO_ID_LEN int NOT NULL,
	CUER_IDENTIFICACION_LEN int NOT NULL,
	CUER_COD_MILITAR_LEN int NOT NULL,
	CUER_PRIMER_NOMBRE_LEN int NOT NULL,
	CUER_SEGUNDO_NOMBRE_LEN int NOT NULL,
	CUER_PRIMER_APELLIDO_LEN int NOT NULL,
	CUER_SEGUNDO_APELLIDO_LEN int NOT NULL,
	CUER_EMBARGO_LEN int NOT NULL,
	CUER_INGRESO_BASE_LEN int NOT NULL,
	CUER_VALOR_LEN int NOT NULL,
	CUER_PERIODO_LEN int NOT NULL,
	CUER_GRADO_LEN int NOT NULL,
	CUER_UNIDAD_OPERATIVA_LEN int NOT NULL,
	FIN_LEN int NOT NULL,
	FIN_CONSEC_LEN int NOT NULL,
	FIN_INDICADOR_CONTROL_LEN int NOT NULL,
	FIN_SUM_APORTES_LEN int NOT NULL,
	FIN_COD_FIN_LEN int NOT NULL,
	CONSTRAINT PK_PARAM_CARG_NOMINA PRIMARY KEY (PARAM_ARCHIVO_CARGUE_NOMINA_ID)
);
END
