IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FRT_FORMATO]') AND type in (N'U'))
DROP TABLE [dbo].[FRT_FORMATO]

CREATE TABLE [dbo].[FRT_FORMATO](
	[FRT_ID] [int] IDENTITY(1,1) NOT NULL,
	[FRT_DESCRIPCION] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[FRT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
