IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MDE_MEDIOS_DE_ENVIO]') AND type in (N'U'))
DROP TABLE [dbo].[MDE_MEDIOS_DE_ENVIO]

CREATE TABLE [dbo].[MDE_MEDIOS_DE_ENVIO](
	[MDE_ID] [int] IDENTITY(1,1) NOT NULL,
	[MDE_DESCRIPCION] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[MDE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
