/*
Nombre: CrearBloqueo
Descripcion: Crea bloqueo
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/
CREATE PROCEDURE[dbo].CrearBloqueo
@ID int,
@CODIGO int,
@CONCEPTO nvarchar(25),
@DIASMORA nvarchar(25),
@REVERSIBLE bit,
@ACELERACIONDEUDA bit,
@FECHAMODIFICACION datetime,
@MODIFICADOPOR int,
@ESTADO bit
AS 
BEGIN
INSERT INTO GA2..MOD_BLOQUEOS
(MOD_B_CODIGO,
MOD_B_CONCEPTO,
MOD_B_DIAS_MORA,
MOD_B_REVERSIBLE,
MOD_B_ACELERACION_DEUDA,
MOD_B_FECHA_MODIFICACION,
MOD_B_MODIFICADO_POR,
MOD_B_ESTADO) 
VALUES(@CODIGO,
@CONCEPTO,
@DIASMORA,
@REVERSIBLE,
@ACELERACIONDEUDA,
@FECHAMODIFICACION,
@MODIFICADOPOR,
@ESTADO)
END