IF OBJECT_ID('ObtenerProgramaEducativo', 'P') > 0
BEGIN
	DROP PROCEDURE ObtenerProgramaEducativo
END
GO
CREATE PROCEDURE ObtenerProgramaEducativo
	@ENE_ID_FK					UNIQUEIDENTIFIER
AS
BEGIN	
	SELECT PGN_ID, UPPER(PGE_DESCRIPCION) AS PGE_DESCRIPCION
	FROM PGE_PROGRAMA_EDUCATIVO
	INNER JOIN PGN_PROGRAMA_ENTIDAD	ON PGE_PROGRAMA_EDUCATIVO.PGE_ID = PGN_PROGRAMA_ENTIDAD.PGE_ID_FK
	WHERE PGN_PROGRAMA_ENTIDAD.ENE_ID_FK = @ENE_ID_FK
END	