-- =============================================
-- Author:		Oscar Julian Rojas
-- Create date: 24/04/2021
-- Description:	SP para la validacion de usuario
-- =============================================
CREATE PROCEDURE [dbo].[LoginPaaUser]
@TID_ID integer,
@CLI_IDENTIFICACION nvarchar(15),
@CLI_FECHA_EXPEDICION nvarchar(12),
@DRC_CELULAR nvarchar(15)
AS 
BEGIN
SELECT CLI_ID, CLI_CODIGO_MILITAR, TPA_ID, TID_ID, CLI_IDENTIFICACION,
DPC_ID_IDENTIFICACION_EXPEDIDA, CLI_FECHA_EXPEDICION, CLI_PRIMER_NOMBRE,
CLI_SEGUNDO_NOMBRE, CLI_PRIMER_APELLIDO, CLI_SEGUNDO_APELLIDO, ECL_ID, GRD_ID,
CLI_FECHA_INSCRIPCION, CLI_UNIDAD, CLI_FECHA_ALTA, CLI_ENVIAR_INFORMACION, CTS_SLP,
CLI_ID_PATROCINADOR, CLI_PARTICIPACION, CAT_SEXO, CAT_ESTADO_CIVIL, DPC_ID,
CLI_FECHA_ADQUISION_VIVIENDA, CLI_PROFESION, CLI_ACTIVIDAD, CLI_INGRESOS_MENSUALES,
CLI_EGRESOS_MENSUALES, CLI_TOTAL_ACTIVOS, CLI_TOTAL_PASIVOS, CLI_INGRESOS_ADICIONALES,
CLI_CONCEPTO_ADICIONALES, CLI_FECHA_ACTUALIZACION_DATOS, UEJ_ID, TVV_ID, CLI_REGIMEN,
CLI_DERECHO_ADQUIRIDO, CLI_TASA_APORTE, CLI_TASA_VOLUNTARIA, CLI_VALIDACION, CLI_FECHA_NACIMIENTO,
FRZ_ID, CLI_VALOR_TRANSFERENCIAS, CLI_RESOLUCION, CLI_TASA_SALARIO_BASE, CVF_ID, GVF_ID, GSF_ID,
CLI_MODELO_SUBSIDIO, CLI_PARTICIPACION_SUBSIDIO, ECL_ID_AVAL FROM CIE_CLIENTE CLI
INNER JOIN CIE_CLIENTE_DIRECCION CCR ON CLI.CLI_ID = CCR.DRC_CLI_ID
WHERE
CLI.TID_ID=@TID_ID AND 
CLI.CLI_IDENTIFICACION=@CLI_IDENTIFICACION  AND 
CLI.CLI_FECHA_EXPEDICION=@CLI_FECHA_EXPEDICION AND 
CCR.DRC_CELULAR=@DRC_CELULAR

END;