/*
Nombre: CrearSolicCreditoInfTecnica
Descripcion: Crea o acualiza los datos Tecnicos de la Solicitud de Credito
Elaboro: German Eduardo Guarnizo
Fecha: Abril 30 de 2021
*/
Create PROCEDURE[dbo].[CrearSolicCreditoInfTecnica]
@SIT_ID uniqueidentifier,
@SOC_ID uniqueidentifier,
@SIT_VALOR_AVALUO_COMERCIAL decimal(22,0),
@SIT_VALOR_VENTA_INMUEBLE decimal(22, 0),
@SIT_CONSIDERACIONES_FINALES varchar(500),
@SIT_DECLARA_CUMPLIMIENTO varchar(500),
@SIT_CONDICIONES_SALVEADES varchar(500),
@SIT_CONCEPTO_EST_TECNICO varchar(500),
@SIT_CREADO_POR uniqueidentifier,
@SIT_FECHA_CREACION datetime

AS
BEGIN
Declare @mIdTecnico int
	Select @mIdTecnico = count(*) From SIT_SOLICITUD_INF_TECNICA Where SOC_ID = @SOC_ID
	If @mIdTecnico = 0
	Begin
		--- Creo los datos del conyugue
		Insert into SIT_SOLICITUD_INF_TECNICA (SIT_ID, SOC_ID, SIT_VALOR_AVALUO_COMERCIAL, SIT_VALOR_VENTA_INMUEBLE,
											   SIT_CONSIDERACIONES_FINALES, SIT_DECLARA_CUMPLIMIENTO, SIT_CONDICIONES_SALVEADES,
											   SIT_CONCEPTO_EST_TECNICO,
											   SIT_CREADO_POR, SIT_FECHA_CREACION, SIT_ACTUALIZADO_POR, SIT_FECHA_ACTUALIZA
											)
						
		Values(@SIT_ID, @SOC_ID, @SIT_VALOR_AVALUO_COMERCIAL, @SIT_VALOR_VENTA_INMUEBLE,
				@SIT_CONSIDERACIONES_FINALES, @SIT_DECLARA_CUMPLIMIENTO, @SIT_CONDICIONES_SALVEADES,
				@SIT_CONCEPTO_EST_TECNICO,
				@SIT_CREADO_POR, @SIT_FECHA_CREACION, @SIT_CREADO_POR, @SIT_FECHA_CREACION
			)


	End
	Else
	Begin
		Update SIT_SOLICITUD_INF_TECNICA Set SIT_VALOR_AVALUO_COMERCIAL=@SIT_VALOR_AVALUO_COMERCIAL,
											 SIT_VALOR_VENTA_INMUEBLE = @SIT_VALOR_VENTA_INMUEBLE,
											 SIT_CONSIDERACIONES_FINALES = @SIT_CONSIDERACIONES_FINALES,
											 SIT_DECLARA_CUMPLIMIENTO = @SIT_DECLARA_CUMPLIMIENTO,
											 SIT_CONDICIONES_SALVEADES = @SIT_CONDICIONES_SALVEADES,
											 SIT_CONCEPTO_EST_TECNICO = @SIT_CONCEPTO_EST_TECNICO,
											 SIT_ACTUALIZADO_POR = @SIT_CREADO_POR, SIT_FECHA_ACTUALIZA = @SIT_FECHA_CREACION
        Where SOC_ID = @SOC_ID

	End
	-- Retorno los Datos Tecnicos
	Select  * From SIT_SOLICITUD_INF_TECNICA
	 Where SOC_ID = @SOC_ID
END
