USE [GA2]
GO
/****** Object:  StoredProcedure [dbo].[CrearActividadFlujo]    Script Date: 7/07/2021 12:30:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Cristian gonzalez>
-- Create date: <07/05/2021>
-- Description:	<SP para la creación de Flujo Actividad>
-- =============================================
CREATE PROCEDURE [dbo].[CrearActividadFlujo]
	@FLU_ID int  
	,@TAC_ID int  
	,@AFL_ORDEN int  
	,@AFL_TIEMPO int  
	,@AFL_ACTIVIDAD_AUTOMATICA char(1)  
	,@AFL_ACTIVIDAD_PRINCIPAL char(1)  
	,@AFL_PUEDE_DELEGAR char(1)  
	,@AFL_CARGA_ARCHIVOS char(1)  
	,@AFL_VISUALIZA_ARCHIVOS char(1)  
	,@AFL_CAPTURA_DATOS_TEC char(1)  
	,@AFL_CAPTURA_DATOS_JUR char(1)  
	,@AFL_CAPTURA_DATOS_FIN char(1)  
	,@AFL_VISUALIZA_DATOS_BAS char(1)  
	,@AFL_VIISUALIZA_DATOS_GAR char(1)  
	,@AFL_VISUALIZA_DATOS_FIN char(1)  
	,@AFL_GENERA_PDF_RESUMEN char(1)  
	,@AFL_CONSULTA_BURO char(1)  
	,@AFL_ENVIO_NOTIFICACION char(1) 
	,@AFL_ENVIO_NOTIFICACION_VENC char(1) 
	,@AFL_ENVIA_NOTIFICACION_CLIENTE  char(1) 
	,@AFL_ESTADO int  
	,@AFL_CREADO_POR uniqueidentifier  
	,@AFL_FECHA_CREACION datetime  
	,@AFL_MODIFICADO_POR uniqueidentifier 
	,@AFL_FECHA_MODIFICACION datetime 
AS 
BEGIN
 IF  Not EXISTS (SELECT TOP 1 * FROM [dbo].[AFL_ACTIVIDAD_FLUJO] WITH (NOLOCK) WHERE TAC_ID = @TAC_ID and FLU_ID = @FLU_ID) 
BEGIN
			INSERT INTO [GA2].[dbo].[AFL_ACTIVIDAD_FLUJO]
			(
				FLU_ID
				,TAC_ID
				,AFL_ORDEN
				,AFL_TIEMPO
				,AFL_ACTIVIDAD_AUTOMATICA
				,AFL_ACTIVIDAD_PRINCIPAL
				,AFL_PUEDE_DELEGAR
				,AFL_CARGA_ARCHIVOS
				,AFL_VISUALIZA_ARCHIVOS
				,AFL_CAPTURA_DATOS_TEC
				,AFL_CAPTURA_DATOS_JUR
				,AFL_CAPTURA_DATOS_FIN
				,AFL_VISUALIZA_DATOS_BAS
				,AFL_VIISUALIZA_DATOS_GAR
				,AFL_VISUALIZA_DATOS_FIN
				,AFL_GENERA_PDF_RESUMEN
				,AFL_CONSULTA_BURO
				,AFL_ENVIO_NOTIFICACION
				,AFL_ENVIO_NOTIFICACION_VENC
				,AFL_ENVIA_NOTIFICACION_CLIENTE
				,AFL_ESTADO
				,AFL_CREADO_POR
				,AFL_FECHA_CREACION
				,AFL_MODIFICADO_POR
				,AFL_FECHA_MODIFICACION
			) 
				VALUES
					(    
				@FLU_ID
				,@TAC_ID
				,@AFL_ORDEN
				,@AFL_TIEMPO
				,@AFL_ACTIVIDAD_AUTOMATICA
				,@AFL_ACTIVIDAD_PRINCIPAL
				,@AFL_PUEDE_DELEGAR
				,@AFL_CARGA_ARCHIVOS
				,@AFL_VISUALIZA_ARCHIVOS
				,@AFL_CAPTURA_DATOS_TEC
				,@AFL_CAPTURA_DATOS_JUR
				,@AFL_CAPTURA_DATOS_FIN
				,@AFL_VISUALIZA_DATOS_BAS
				,@AFL_VIISUALIZA_DATOS_GAR
				,@AFL_VISUALIZA_DATOS_FIN
				,@AFL_GENERA_PDF_RESUMEN
				,@AFL_CONSULTA_BURO
				,@AFL_ENVIO_NOTIFICACION
				,@AFL_ENVIO_NOTIFICACION_VENC
				,@AFL_ENVIA_NOTIFICACION_CLIENTE
				,@AFL_ESTADO
				,@AFL_CREADO_POR
				,@AFL_FECHA_CREACION
				,@AFL_MODIFICADO_POR
				,@AFL_FECHA_MODIFICACION
					)
					SELECT 
					FLU_ID
				,TAC_ID
				,AFL_ORDEN
				,AFL_TIEMPO
				,AFL_ACTIVIDAD_AUTOMATICA
				,AFL_ACTIVIDAD_PRINCIPAL
				,AFL_PUEDE_DELEGAR
				,AFL_CARGA_ARCHIVOS
				,AFL_VISUALIZA_ARCHIVOS
				,AFL_CAPTURA_DATOS_TEC
				,AFL_CAPTURA_DATOS_JUR
				,AFL_CAPTURA_DATOS_FIN
				,AFL_VISUALIZA_DATOS_BAS
				,AFL_VIISUALIZA_DATOS_GAR
				,AFL_VISUALIZA_DATOS_FIN
				,AFL_GENERA_PDF_RESUMEN
				,AFL_CONSULTA_BURO
				,AFL_ENVIO_NOTIFICACION
				,AFL_ENVIO_NOTIFICACION_VENC
				,AFL_ENVIA_NOTIFICACION_CLIENTE
				,AFL_ESTADO
				,AFL_CREADO_POR
				,AFL_FECHA_CREACION
				,AFL_MODIFICADO_POR
				,AFL_FECHA_MODIFICACION
					FROM
						[AFL_ACTIVIDAD_FLUJO]
					WHERE FLU_ID=@FLU_ID
		END
		ELSE 
		BEGIN
		 SELECT 'EL REGISTRO YA EXISTE'
		 END
END



