USE [GA2]
GO
/****** Object:  StoredProcedure [dbo].[CrearSimulacionCliente]    Script Date: 6/07/2021 5:08:42 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
Nombre: CrearSimulacionCliente
Descripcion: Crear el detalle de la simulacion del credito del cliente, de acuerdo a los
             parametros y datos del cliente. Retornando el detalle de la amportizacion
Elaboro: German Eduardo Guarnizo
Fecha: Abril 7 de 2021
*/
ALTER PROCEDURE [dbo].[CrearSimulacionCliente] 
@NUMERO_DOCUMENTO varchar(15),
@TIPO_VIVIENDA VARCHAR(1),  
@VALOR BIGINT,
@TIPO_ABONO VARCHAR(1),
@SUBSIDIO VARCHAR(1)

AS	
BEGIN

DECLARE 
@SALARIO INT,
@TOTAL_INGRESOS INT,
@TOTAL_EGRESOS INT,
@FACTOR_SUBSIDIO INT,
@ABONO_MES INT,
@TASA_MV DECIMAL(20,17),
@TASA_EA DECIMAL(20,17),
@TASA_MV1 DECIMAL(20,17),
@SOLDADO VARCHAR(1),
@VIVIENDA_VIS VARCHAR(1),
@DERECHO_ALIVIO_TASA VARCHAR(1),
@DERECHO_ALIVIO_CUOTA VARCHAR(1),
@FECHA_DESEMBOLSO DATE,
@FECHA_AFILIA DATE,
@SMMLV INT,
@SMMLV_PROY INT,
@VALOR_FINANCIA BIGINT,
@TASA_CREDITO DECIMAL(5,2),
@VALOR_ALIVIO INT,
@TASA_FRECH DECIMAL(5,2),
@VALOR_SUBSIDIO BIGINT,
@VALOR_SUBSIDIO1 BIGINT,
@FECHA_SUBSIDIO VARCHAR(10),
@SALDO_AN_SUBSIDIO BIGINT,
@VALOR_PRESTAMO BIGINT,
@MESES_LEY INT,
@CAPACIDAD_PAGO FLOAT,
@CAPACIDAD_MIXTA FLOAT,
@CAPACIDAD_MIXTA1 FLOAT,
@VALOR_TERREMOTO FLOAT,
@CUOTA INT,
@TASA_VIDA DECIMAL(5,4),
@TASA_TERREMOTO DECIMAL(5,4),
@PORC_EXTRAPRIMA DECIMAL(5,2),
@FECHA_CUOTA DATE,
@SALDO BIGINT,
@INTERES INT,
@VALOR_VIDA INT,
@VALOR_CAPITAL INT,
@FECHA_PAGO DATE,
@VALOR_ABONO FLOAT,
@VALOR_ABONO1 FLOAT,
@INTERES_REDUCCION INT,
@COBRO_FONVI INT,
@POTENCIA DECIMAL(20,17),
@CUOTAS_APORT INT,
@TIPO_ALIVIO VARCHAR(1),
@ID_SOLIC uniqueidentifier,
@DEPTO_INM INT,
@CIUDA_INM INT,
@CONTA INT,
@PORC_LIBRANZA decimal(5,2),
@MESES_SUBSIDIO int

--@CUOTAMINIMA VARCHAR(1) ='N',
--@CONTADOR INT

SET @VIVIENDA_VIS = 'N'
SET @DERECHO_ALIVIO_TASA = 'N'
SET @DERECHO_ALIVIO_CUOTA = 'N'
SET @TIPO_ALIVIO = 'N'

SELECT @SALARIO= FIN.SDF_VALOR_SALARIO, @TOTAL_INGRESOS = SDF_VALOR_TOTAL_INGRESOS, @TOTAL_EGRESOS= SDF_VALOR_TOTAL_EGRESOS,
	@FACTOR_SUBSIDIO = CASE WHEN GRD_FACTOR_SBS IS NULL THEN 0 ELSE GRD_FACTOR_SBS END,
	@SOLDADO = CASE WHEN GRD.CTG_ID = 4 THEN 'S' ELSE 'N' END,
	@FECHA_AFILIA = PER.SDP_FECHA_AFILIACION, @CUOTAS_APORT = SDP_CUOTAS,
	@ID_SOLIC = PER.SLS_ID,
	@DEPTO_INM = PER.DPD_ID_INMUEBLE,
	@CIUDA_INM = DPC_ID_INMUEBLE, 
	@PORC_EXTRAPRIMA = SLS.SLS_PORC_EXTRAPRIMA
FROM SDP_SIMULACION_DATOS_PERSONALES PER With(NoLock) LEFT JOIN GRD_GRADO GRD ON (PER.GRD_ID = GRD.GRD_ID), 
     SDF_SIMULACION_DATOS_FINANCIEROS FIN With(NoLock), SLS_SOLICITUD_SIMULACION SLS With(NoLock)
WHERE PER.SDP_NUMERO_DOCUMENTO = @NUMERO_DOCUMENTO AND PER.SLS_ID = FIN.SLS_ID  
  And PER.SLS_ID = SLS.SLS_ID
IF @SALARIO IS NULL
BEGIN
	SET @SALARIO=0
	SET @TOTAL_INGRESOS=0
	SET @TOTAL_EGRESOS=0
	SET @FACTOR_SUBSIDIO =0
	SET @SOLDADO ='N'
	SET @FECHA_AFILIA = GETDATE()
	SET @CUOTAS_APORT = 0
END

--DETERMINA EL ALICIO O EL PROCENTAJE DE TASA FRECH
SET @VALOR_ALIVIO =0
SET @TASA_FRECH =0


IF @TIPO_VIVIENDA = 'N'
BEGIN
		SELECT @VALOR_ALIVIO = PRR_ALIVIO_CUOTA FROM PRR_RANGO_SUBSIDIO WHERE @VALOR BETWEEN PRR_VALOR_INICIAL AND PRR_VALOR_FINAL
		If @VALOR_ALIVIO > 0
		Begin
		   Set @DERECHO_ALIVIO_CUOTA = 'S'
		   Set @TIPO_ALIVIO = 'X'
		End

		SELECT @TASA_FRECH = PRR_TASA_FREC FROM PRR_RANGO_SUBSIDIO WHERE @VALOR BETWEEN PRR_VALOR_INICIAL AND PRR_VALOR_FINAL
		If @TASA_FRECH > 0
		Begin
		   Set @DERECHO_ALIVIO_TASA = 'S'
		   Set @TIPO_ALIVIO = 'F'
	    END
		   
END
--SELECCONA PARAMEROS
SET @POTENCIA = 1.0/12.0000000000000000000

SELECT 
	@FECHA_DESEMBOLSO = DATEADD(DD,PRM_DIAS_DESEMBOLSO, GETDATE()) ,
	@FECHA_SUBSIDIO = dbo.UDF_FechaFinMes(CASE WHEN @SOLDADO ='S' THEN DATEADD(MM, PRM_MES_SUBSIDIO_SOL,@FECHA_AFILIA) ELSE DATEADD(MM, PRM_MES_SUBSIDIO_SOL - @CUOTAS_APORT+1,DATEADD(DD,PRM_DIAS_DESEMBOLSO, GETDATE())) END ),
	@VALOR_FINANCIA = ROUND(CASE WHEN @VALOR <= PRM_NO_SALARIO_MIN_VIS * PRM_SMLV THEN @VALOR *  PRM_PORC_FINANCIA_VIS/100.0 ELSE @VALOR *  PRM_PORC_FINANCIA_NO_VIS/100.0 END,0),
	@VIVIENDA_VIS = CASE WHEN @VALOR <= PRM_NO_SALARIO_MIN_VIS * PRM_SMLV THEn 'S' ELSE 'N' END,
	@MESES_LEY = CASE WHEN @TIPO_ALIVIO = 'F' THEN PRM_MESES_LEY_FRECH ELSE PRM_MESES_LEY_ALIV END,
	@PORC_LIBRANZA = PRM_PORC_LEY_LIBRANZA, @MESES_SUBSIDIO = PRM_MESES_SUBSIDIO_CUOTA,
	@SMMLV_PROY = PRM_SMLV * POWER(1+PRM_PORC_INCREMENTO_ANUAL/100.0,DATEDIFF(DD,@FECHA_AFILIA, @FECHA_SUBSIDIO)/365.0 )
FROM PRM_SIMULADOR


--  Tomo parametros del Simulador
Select @TASA_EA = SIM_TASA_EA, 
       @TASA_MV = POWER(1.0 + SIM_TASA_EA /100.0,(@POTENCIA))-1.0, @TASA_MV1 = POWER(1 + (CONVERT(DECIMAL(20,17),SIM_TASA_EA - @TASA_FRECH)) /100.0,(@POTENCIA))-1
From SIM_SIMULADOR Where SIM_ID = 1

--- Tomo los parametros de seguros d ela tarifa general
Select  Top 1 @TASA_VIDA = SEG_VIDA/100.0, @TASA_TERREMOTO = SEG_TODO_RIESGO / 100.0,
              @VALOR_TERREMOTO =  ROUND(@VALOR * SEG_TODO_RIESGO / 100.0,0)
  From PARAM_SEGURO
Where SEG_ESTADO=1
Order by SEG_FECHA_MODIFICACION DESC

-- Obtengo las Excepciones 
IF @DEPTO_INM IS NULL
  SET @DEPTO_INM = 0

IF @CIUDA_INM IS NULL
  SET @CIUDA_INM = 0

SET @CONTA = 0
Select  @CONTA = COUNT(*)
 From PARAM_SEGURO_UBICACION
Where SEU_ESTADO=1
  AND DPD_ID = @DEPTO_INM
  AND DPC_ID = @CIUDA_INM
IF  @CONTA > 0
Begin
	Select  TOP 1  @TASA_TERREMOTO = SEU_TODO_RIESGO / 100.0,
                   @VALOR_TERREMOTO =  ROUND(@VALOR * SEU_TODO_RIESGO / 100.0,0)
	 From PARAM_SEGURO_UBICACION
	Where SEU_ESTADO=1
	  AND DPD_ID = @DEPTO_INM
	  AND DPC_ID = @CIUDA_INM
	Order by SEU_FECHA_MODIFICACION DESC
END
--- manejo de la Extraprima
 IF @PORC_EXTRAPRIMA > 0 
 Begin
    Set @TASA_VIDA = @TASA_VIDA + (@TASA_VIDA*(@PORC_EXTRAPRIMA/100))
 End
--SET @TOTAL_INGRESOS =  3586374 
--SET @TOTAL_EGRESOS =400000
--SET @SALARIO =  1901498 


--SLECCINA SALIRAIO MINIMOM PRYECTADO

SET @VALOR_SUBSIDIO = @SMMLV_PROY * @FACTOR_SUBSIDIO
If @SUBSIDIO = 'N'
  SET @VALOR_SUBSIDIO = 0
SET @CAPACIDAD_PAGO = (@TOTAL_INGRESOS-@TOTAL_EGRESOS) *(@PORC_LIBRANZA/100)
IF @CAPACIDAD_PAGO < 0
	SET @CAPACIDAD_PAGO =0

--Select 'TI:',@TOTAL_INGRESOS,'TE:',@TOTAL_EGRESOS,'CP: ',@CAPACIDAD_PAGO,' VS:',@VALOR_SUBSIDIO

IF @TIPO_ABONO ='N'
BEGIN
	SET @VALOR_ABONO = 0
	SET @CAPACIDAD_MIXTA  = @CAPACIDAD_PAGO 	
END 
ELSE
BEGIN
	if @TIPO_ABONO ='M'
	begin
		SET @VALOR_ABONO = ROUND(@SALARIO *0.21,0)
		SET @CAPACIDAD_MIXTA  = @CAPACIDAD_PAGO
	end
	else
	begin
		SET @VALOR_ABONO = ROUND(@SALARIO *0.21 *12 ,0)
		SET @CAPACIDAD_MIXTA  = @CAPACIDAD_PAGO 
	end
END
--SET  @VALOR_ABONO  = 399315 --BORRAR



--SLEECCIONA EL VALOR DEL PRESTAMO
SET @VALOR_PRESTAMO = (@CAPACIDAD_MIXTA  - @VALOR_TERREMOTO )*((1-POWER(1/(1+(@TASA_MV+@TASA_VIDA )),@MESES_LEY) )/(@TASA_MV+@TASA_VIDA))

--Select 'VF:',@VALOR_FINANCIA,'VA:',@VALOR_ABONO,'CM:',@CAPACIDAD_MIXTA,'VP:',@VALOR_PRESTAMO,'VT:',@VALOR_TERREMOTO,'SV:	',@TASA_VIDA,'ML',@MESES_LEY

IF @VALOR_FINANCIA < @VALOR_PRESTAMO
  Set @VALOR_PRESTAMO = @VALOR_FINANCIA


--INICIO:
--IF @CUOTAMINIMA ='S'
--BEGIN
--	IF @VALOR_PRESTAMO > @VALOR_SUBSIDIO
--		SET @CAPACIDAD_MIXTA  = (@VALOR_PRESTAMO - @VALOR_SUBSIDIO)/((1-POWER(1/(1+(@TASA_MV+@TASA_VIDA )),@MESES_LEY) )/(@TASA_MV+@TASA_VIDA))
--END

CREATE TABLE #TMP_SIMULADOR (CUOTA int, FECHA_CORTE DATE, FECHA_PAGO DATE, SALDO BIGINT, INTERESES INT, CAPITAL INT, SEGURO_VIDA INT, SEGURO_TERREMOTO INT, CUOTA_TOTAL INT, ABONO_EXTRA INT, ABONO_MENSUAL INT, CUOTA_UNIDAD_PAGADORA INT, INTERES_REDUCCION INT, CUOTA_REDUCCION INT, COBRO_FONVIVIENDA INT)

																																																							
SET @CUOTA =1
SET @FECHA_CUOTA = CONVERT(DATE, CONVERT(VARCHAR(8),@FECHA_DESEMBOLSO,120)+'01') 
SET @SALDO = @VALOR_PRESTAMO


IF  @TIPO_ALIVIO ='F' AND @TIPO_ABONO <> 'A'
BEGIN

	WHILE (@CUOTA <= @MESES_LEY and @SALDO >0)
	BEGIN
		SET @INTERES = ROUND(@SALDO *@TASA_MV,0)
		SET @VALOR_VIDA = ROUND(@SALDO *@TASA_VIDA,0)
	
		SET @FECHA_PAGO = dbo.UDF_FechaFinMes(DATEADD(MM,1,@FECHA_CUOTA))
	 
		IF @FECHA_SUBSIDIO = @FECHA_PAGO 
			SET @VALOR_SUBSIDIO1 = @VALOR_SUBSIDIO
		ELSE
			SET @VALOR_SUBSIDIO1 =0

		SET @VALOR_ABONO1 = @VALOR_ABONO

		SET @VALOR_CAPITAL = @CAPACIDAD_MIXTA +@VALOR_ABONO1 -@INTERES -@VALOR_VIDA -@VALOR_TERREMOTO

		IF @CUOTA <= @MESES_SUBSIDIO
			SET @INTERES_REDUCCION = ROUND(@SALDO * @TASA_MV1,0)
		ELSE
			SET @INTERES_REDUCCION = ROUND(@SALDO * @TASA_MV,0)

		SET @COBRO_FONVI =@INTERES -@INTERES_REDUCCION
		SET @CAPACIDAD_MIXTA1 =@CAPACIDAD_MIXTA-@COBRO_FONVI

		SET @SALDO = @SALDO -@VALOR_CAPITAL -@VALOR_SUBSIDIO1 -@COBRO_FONVI

		INSERT INTO #TMP_SIMULADOR 
		SELECT @CUOTA, dbo.UDF_FechaFinMes(@FECHA_CUOTA), @FECHA_PAGO , @SALDO, @INTERES,@VALOR_CAPITAL, @VALOR_VIDA, @VALOR_TERREMOTO, @CAPACIDAD_MIXTA, 
			@VALOR_SUBSIDIO1, @VALOR_ABONO1, @CAPACIDAD_PAGO, @INTERES_REDUCCION, @CAPACIDAD_MIXTA1 , @COBRO_FONVI 
		SET @CUOTA =@CUOTA + 1
		SET @FECHA_CUOTA = DATEADD(MM,1,@FECHA_CUOTA)
	END
END

IF  @TIPO_ALIVIO ='F' AND @TIPO_ABONO = 'A'
BEGIN

	WHILE (@CUOTA <= @MESES_LEY and @SALDO >0)
	BEGIN
		SET @INTERES = ROUND(@SALDO *@TASA_MV,0)
		SET @VALOR_VIDA = ROUND(@SALDO *@TASA_VIDA,0)
		
		SET @FECHA_PAGO = dbo.UDF_FechaFinMes(DATEADD(MM,1,@FECHA_CUOTA))
	 
		IF @FECHA_SUBSIDIO = @FECHA_PAGO 
			SET @VALOR_SUBSIDIO1 = @VALOR_SUBSIDIO
		ELSE
			SET @VALOR_SUBSIDIO1 =0

		
		IF MONTH(@FECHA_CUOTA) = 12
		BEGIN
			IF @CUOTA <12
				SET @VALOR_ABONO1 = @VALOR_ABONO*@CUOTA/12.0
			ELSE
				SET @VALOR_ABONO1  = @VALOR_ABONO
		END
		ELSE
			SET @VALOR_ABONO1 = 0

		SET @VALOR_CAPITAL = @CAPACIDAD_MIXTA +@VALOR_ABONO1 -@INTERES -@VALOR_VIDA -@VALOR_TERREMOTO
		IF @CUOTA <= @MESES_SUBSIDIO
			SET @INTERES_REDUCCION = ROUND(@SALDO * @TASA_MV1,0)
		ELSE
			SET @INTERES_REDUCCION = ROUND(@SALDO * @TASA_MV,0)

			SET @COBRO_FONVI =@INTERES -@INTERES_REDUCCION
			SET @CAPACIDAD_MIXTA1 =@CAPACIDAD_MIXTA-@COBRO_FONVI

		SET @SALDO = @SALDO -@VALOR_CAPITAL -@VALOR_SUBSIDIO1 -@COBRO_FONVI

		INSERT INTO #TMP_SIMULADOR 
		SELECT @CUOTA, dbo.UDF_FechaFinMes(@FECHA_CUOTA), @FECHA_PAGO , @SALDO, @INTERES,@VALOR_CAPITAL, @VALOR_VIDA, @VALOR_TERREMOTO, @CAPACIDAD_MIXTA, 
			@VALOR_SUBSIDIO1, @VALOR_ABONO1, @CAPACIDAD_PAGO, @INTERES_REDUCCION, @CAPACIDAD_MIXTA1 , @COBRO_FONVI 
		SET @CUOTA =@CUOTA + 1
		SET @FECHA_CUOTA = DATEADD(MM,1,@FECHA_CUOTA)
	END
END

IF  @TIPO_ALIVIO <>'F' AND @TIPO_ABONO <> 'A'
BEGIN
	SET @INTERES_REDUCCION = @VALOR_ALIVIO 
	WHILE (@CUOTA <= @MESES_LEY and @SALDO >0)
	BEGIN
		if @CUOTA =85
			set @INTERES_REDUCCION =0
		SET @INTERES = ROUND(@SALDO *@TASA_MV1,0)
	
		SET @VALOR_VIDA = ROUND(@SALDO *@TASA_VIDA,0)
		
		SET @FECHA_PAGO = dbo.UDF_FechaFinMes(DATEADD(MM,1,@FECHA_CUOTA))

		IF @FECHA_SUBSIDIO = @FECHA_PAGO 
			SET @VALOR_SUBSIDIO1 = @VALOR_SUBSIDIO
		ELSE
			SET @VALOR_SUBSIDIO1 =0

		SET @VALOR_CAPITAL = @CAPACIDAD_MIXTA+@VALOR_ABONO -@INTERES -@VALOR_VIDA -@VALOR_TERREMOTO
		SET @SALDO = @SALDO -@VALOR_CAPITAL-@INTERES_REDUCCION -@VALOR_SUBSIDIO1

		INSERT INTO #TMP_SIMULADOR 
		SELECT @CUOTA, dbo.UDF_FechaFinMes(@FECHA_CUOTA), @FECHA_PAGO , @SALDO, @INTERES,@VALOR_CAPITAL, @VALOR_VIDA, @VALOR_TERREMOTO, @CAPACIDAD_MIXTA, 
			CASE WHEN @FECHA_SUBSIDIO = @FECHA_PAGO  THEN @VALOR_SUBSIDIO ELSE 0 END, @VALOR_ABONO, @CAPACIDAD_PAGO, @INTERES_REDUCCION, @CAPACIDAD_MIXTA-@INTERES_REDUCCION , @INTERES_REDUCCION 
		SET @CUOTA =@CUOTA + 1
		SET @FECHA_CUOTA = DATEADD(MM,1,@FECHA_CUOTA)
	END
END


IF  @TIPO_ALIVIO <>'F' AND @TIPO_ABONO = 'A'
BEGIN
	SET @INTERES_REDUCCION = @VALOR_ALIVIO 
	WHILE (@CUOTA <= @MESES_LEY and @SALDO >0)
	BEGIN
		if @CUOTA =85
			set @INTERES_REDUCCION =0
		SET @INTERES = ROUND(@SALDO *@TASA_MV1,0)
		SET @VALOR_VIDA = ROUND(@SALDO *@TASA_VIDA,0)
	
		SET @FECHA_PAGO = dbo.UDF_FechaFinMes(DATEADD(MM,1,@FECHA_CUOTA))

		IF @FECHA_SUBSIDIO = @FECHA_PAGO 
			SET @VALOR_SUBSIDIO1 = @VALOR_SUBSIDIO
		ELSE
			SET @VALOR_SUBSIDIO1 =0

		IF MONTH(@FECHA_CUOTA) = 12
		BEGIN
			IF @CUOTA <12
				SET @VALOR_ABONO1 = @VALOR_ABONO*@CUOTA/12.0
			ELSE
				SET @VALOR_ABONO1  = @VALOR_ABONO
		END
		ELSE
			SET @VALOR_ABONO1 = 0

		SET @VALOR_CAPITAL = @CAPACIDAD_MIXTA -@INTERES -@VALOR_VIDA -@VALOR_TERREMOTO
		SET @SALDO = @SALDO-@VALOR_ABONO1 -@VALOR_CAPITAL-@INTERES_REDUCCION -@VALOR_SUBSIDIO1

		INSERT INTO #TMP_SIMULADOR 
		SELECT @CUOTA, dbo.UDF_FechaFinMes(@FECHA_CUOTA), @FECHA_PAGO , @SALDO, @INTERES,@VALOR_CAPITAL, @VALOR_VIDA, @VALOR_TERREMOTO, @CAPACIDAD_MIXTA, 
			CASE WHEN @FECHA_SUBSIDIO = @FECHA_PAGO  THEN @VALOR_SUBSIDIO ELSE 0 END, @VALOR_ABONO1, @CAPACIDAD_PAGO, @INTERES_REDUCCION, @CAPACIDAD_MIXTA-@INTERES_REDUCCION , @INTERES_REDUCCION 
		SET @CUOTA =@CUOTA + 1
		SET @FECHA_CUOTA = DATEADD(MM,1,@FECHA_CUOTA)
	END
END


--IF @CUOTAMINIMA ='N'
--BEGIN
--	SELECT @CONTADOR= COUNT(1) FROM #TMP_SIMULADOR
--	IF @CONTADOR <60
--	BEGIN
--		DROP TABLE #TMP_SIMULADOR
--		SET @CUOTAMINIMA ='S' 
--		GOTO INICIO
--	END
--END

UPDATE #TMP_SIMULADOR SET SALDO =0 WHERE  SALDO < 0

-- ALimento la Informacion de la Simulacion
DECLARE @UNI UNIQUEIDENTIFIER
SET @UNI = NEWID()

Insert Into SMC_SIMULACION_CLIENTE
Select  @UNI, SLS_ID, SDP_ID, @TIPO_VIVIENDA, @VALOR, @TIPO_ALIVIO, @TIPO_ABONO, SDP_NUMERO_DOCUMENTO, @VALOR_PRESTAMO, @TASA_EA, @TASA_MV, @TASA_MV1, @VIVIENDA_VIS, GETDATE(), 'N','N',0, 0,0, NULL 
From SDP_SIMULACION_DATOS_PERSONALES
Where SDP_NUMERO_DOCUMENTO = @NUMERO_DOCUMENTO

Insert Into SMD_SIMULACION_DETALLE
Select NEWID(), @UNI, TMP.*, 0,0,0,0,0,0,0 
From  #TMP_SIMULADOR TMP, SMC_SIMULACION_CLIENTE SIM, SDP_SIMULACION_DATOS_PERSONALES DAT
 Where DAT.SDP_NUMERO_DOCUMENTO = @NUMERO_DOCUMENTO
   AND SIM.SDP_ID = DAT.SDP_ID
   AND SIM.SMC_ID=@UNI

Select SMD.*,@VALOR_PRESTAMO as VALOR_PRESTAMO, @TASA_EA as VALOR_TASA, @VIVIENDA_VIS as VIVIENDA_VIS, @DERECHO_ALIVIO_CUOTA as DERECHO_CUOTA, @DERECHO_ALIVIO_TASA as DERECHO_TASA, @ID_SOLIC as ID_SIMULACION, PR.SIM_MINIMO_MESES_PLAZO as MINIMO_MESES, PR.SIM_MAXIMO_MESES_PLAZO as MAXIMO_MESES, @TASA_MV*100 as VALOR_TASA_NOMINAL, @TASA_MV1 AS VALOR_TASA_NOMINAL_F 
FROM SMD_SIMULACION_DETALLE SMD, SIM_SIMULADOR PR 
Where SMD.SMC_ID = @UNI 
  AND PR.SIM_ID=1 
Order by SMD.SMD_CUOTA

Drop table #TMP_SIMULADOR 

END
