/*
Nombre: CrearSolicCreditoInfJuridica
Descripcion: Crea o acualiza los datos Juridicos de la Solicitud de Credito
Elaboro: German Eduardo Guarnizo
Fecha: Abril 30 de 2021
*/
Create PROCEDURE[dbo].[CrearSolicCreditoInfJuridica]
@SIJ_ID uniqueidentifier,
@SOC_ID uniqueidentifier,
@SIJ_LINDEROS varchar(500),
@SIJ_TIPO_PARQUEADERO varchar(20),
@SIJ_EDAD_JURIDICA int,
@SIJ_FECHA_PRIMER_ACTO date,
@SIJ_TRADICION_INMUEBLE varchar(500),
@SIJ_ANALISIS_ULT_20_AÑOS varchar(500),
@SIJ_ANALISIS_SIT_JURIDICA varchar(500),
@SIJ_ANALISIS_REG_PROP_HOR varchar(500),
@SIJ_ANALISIS_PAZ_Y_SALVO varchar(500),
@SIJ_ANALISIS_VENDEDOR varchar(500),
@SIJ_VIABILIDAD_JUR_NEGOCIO varchar(500),
@SIJ_RECOMENDACIONES varchar(500),
@SIJ_CONCEPTO_JURIDICO_FIN varchar(500),
@SIJ_CONCEPTO_EST_JURIDICO varchar(20),
@SIJ_CREADO_POR uniqueidentifier,
@SIJ_FECHA_CREACION datetime

AS
BEGIN
Declare @mIdJuridico int
	Select @mIdJuridico = count(*) From SIJ_SOLICITUD_INF_JURIDICA Where SOC_ID = @SOC_ID
	If @mIdJuridico = 0
	Begin
		--- Creo los datos del conyugue
		Insert into SIJ_SOLICITUD_INF_JURIDICA (SIJ_ID, SOC_ID, SIJ_LINDEROS, SIJ_TIPO_PARQUEADERO, SIJ_EDAD_JURIDICA,
												SIJ_FECHA_PRIMER_ACTO, SIJ_TRADICION_INMUEBLE, SIJ_ANALISIS_ULT_20_AÑOS,
												SIJ_ANALISIS_SIT_JURIDICA, SIJ_ANALISIS_REG_PROP_HOR, SIJ_ANALISIS_PAZ_Y_SALVO,
												SIJ_ANALISIS_VENDEDOR, SIJ_VIABILIDAD_JUR_NEGOCIO, SIJ_RECOMENDACIONES,
												SIJ_CONCEPTO_JURIDICO_FIN, SIJ_CONCEPTO_EST_JURIDICO,
												SIJ_CREADO_POR, SIJ_FECHA_CREACION, SIJ_ACTUALIZADO_POR, SIJ_FECHA_ACTUALIZA
											)
						
		Values(@SIJ_ID, @SOC_ID, @SIJ_LINDEROS, @SIJ_TIPO_PARQUEADERO, @SIJ_EDAD_JURIDICA,
				@SIJ_FECHA_PRIMER_ACTO, @SIJ_TRADICION_INMUEBLE, @SIJ_ANALISIS_ULT_20_AÑOS,
				@SIJ_ANALISIS_SIT_JURIDICA, @SIJ_ANALISIS_REG_PROP_HOR, @SIJ_ANALISIS_PAZ_Y_SALVO,
				@SIJ_ANALISIS_VENDEDOR, @SIJ_VIABILIDAD_JUR_NEGOCIO, @SIJ_RECOMENDACIONES,
				@SIJ_CONCEPTO_JURIDICO_FIN, @SIJ_CONCEPTO_EST_JURIDICO,
				@SIJ_CREADO_POR, @SIJ_FECHA_CREACION, @SIJ_CREADO_POR, @SIJ_FECHA_CREACION
			)


	End
	Else
	Begin
		Update SIJ_SOLICITUD_INF_JURIDICA Set SIJ_LINDEROS=@SIJ_LINDEROS,
											  SIJ_TIPO_PARQUEADERO = @SIJ_TIPO_PARQUEADERO,
											  SIJ_EDAD_JURIDICA = @SIJ_EDAD_JURIDICA,
											  SIJ_FECHA_PRIMER_ACTO = @SIJ_FECHA_PRIMER_ACTO,
											  SIJ_TRADICION_INMUEBLE = @SIJ_TRADICION_INMUEBLE,
											  SIJ_ANALISIS_ULT_20_AÑOS = @SIJ_ANALISIS_ULT_20_AÑOS,
											  SIJ_ANALISIS_SIT_JURIDICA = @SIJ_ANALISIS_SIT_JURIDICA,
											  SIJ_ANALISIS_REG_PROP_HOR = @SIJ_ANALISIS_REG_PROP_HOR,
											  SIJ_ANALISIS_PAZ_Y_SALVO = @SIJ_ANALISIS_PAZ_Y_SALVO,
											  SIJ_ANALISIS_VENDEDOR = @SIJ_ANALISIS_VENDEDOR,
											  SIJ_VIABILIDAD_JUR_NEGOCIO = @SIJ_VIABILIDAD_JUR_NEGOCIO,
											  SIJ_RECOMENDACIONES = @SIJ_RECOMENDACIONES,
											  SIJ_CONCEPTO_JURIDICO_FIN = @SIJ_CONCEPTO_JURIDICO_FIN,
											  SIJ_CONCEPTO_EST_JURIDICO = @SIJ_CONCEPTO_EST_JURIDICO,
											  SIJ_ACTUALIZADO_POR = @SIJ_CREADO_POR, SIJ_FECHA_ACTUALIZA = @SIJ_FECHA_CREACION
        Where SOC_ID = @SOC_ID

	End
	-- Retorno los Datos Juridicos
	Select  * From SIJ_SOLICITUD_INF_JURIDICA
	 Where SOC_ID = @SOC_ID
END
