USE [GA2]
GO
/****** Object:  StoredProcedure [dbo].[CrearSolicCreditoFinancieros]    Script Date: 6/07/2021 6:26:53 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
Nombre: CrearSolicCreditoFinancieros
Descripcion: Crea o acualiza los datos Financueros del cliente del formulario de solicitud de credito
Elaboro: German Eduardo Guarnizo
Fecha: Abril 12 de 2021
*/
ALTER PROCEDURE [dbo].[CrearSolicCreditoFinancieros] 
@SOF_ID uniqueidentifier,
@SOC_ID uniqueidentifier,
@SOF_CONCEPTO_SALARIO varchar(50),
@SOF_VALOR_CONCEPTO_SALARIO decimal(25,6),
@SOF_CONCEPTO_1 varchar(50),
@SOF_VALOR_CONCEPTO_1 decimal(25,6),
@SOF_CONCEPTO_2 varchar(50),
@SOF_VALOR_CONCEPTO_2 decimal(25,6),
@SOF_CONCEPTO_3 varchar(50),
@SOF_VALOR_CONCEPTO_3 decimal(25,6),
@SOF_CONCEPTO_4 varchar(50),
@SOF_VALOR_CONCEPTO_4 decimal(25,6),
@SOF_CONCEPTO_5 varchar(50),
@SOF_VALOR_CONCEPTO_5 decimal(25,6),
@SOF_CONCEPTO_6 varchar(50),
@SOF_VALOR_CONCEPTO_6 decimal(25,6),
@SOF_VALOR_TOTAL_INGRESOS decimal(25,6),
@SOF_VALOR_TOTAL_EGRESOS decimal(25,6),
@SOF_CREADO_POR uniqueidentifier,
@SOF_FECHA_CREACION datetime

AS
BEGIN
Declare @mIdFinanciero int
	Select @mIdFinanciero = count(*) From SOF_SOLICITUD_INF_FINANCIERA Where SOC_ID = @SOC_ID
	If @mIdFinanciero = 0
	Begin
		--- Creo los datos del conyugue
		Insert into SOF_SOLICITUD_INF_FINANCIERA (SOF_ID, SOC_ID, SOF_CONCEPTO_SALARIO, SOF_VALOR_CONCEPTO_SALARIO, 
										          SOF_CONCEPTO_1,SOF_VALOR_CONCEPTO_1,SOF_CONCEPTO_2,SOF_VALOR_CONCEPTO_2, 
										          SOF_CONCEPTO_3,SOF_VALOR_CONCEPTO_3,SOF_CONCEPTO_4,SOF_VALOR_CONCEPTO_4, 
										          SOF_CONCEPTO_5,SOF_VALOR_CONCEPTO_5,SOF_CONCEPTO_6,SOF_VALOR_CONCEPTO_6, 
												  SOF_VALOR_TOTAL_INGRESOS, SOF_VALOR_TOTAL_EGRESOS,
											      SOF_CREADO_POR,SOF_FECHA_CREACION, SOF_ACTUALIZADO_POR, SOF_FECHA_ACTUALIZA
											)
						
		Values (@SOF_ID, @SOC_ID, @SOF_CONCEPTO_SALARIO, @SOF_VALOR_CONCEPTO_SALARIO, 
			    @SOF_CONCEPTO_1,@SOF_VALOR_CONCEPTO_1,@SOF_CONCEPTO_2,@SOF_VALOR_CONCEPTO_2, 
				@SOF_CONCEPTO_3,@SOF_VALOR_CONCEPTO_3,@SOF_CONCEPTO_4,@SOF_VALOR_CONCEPTO_4, 
				@SOF_CONCEPTO_5,@SOF_VALOR_CONCEPTO_5,@SOF_CONCEPTO_6,@SOF_VALOR_CONCEPTO_6, 
				@SOF_VALOR_TOTAL_INGRESOS, @SOF_VALOR_TOTAL_EGRESOS,
				@SOF_CREADO_POR,@SOF_FECHA_CREACION, @SOF_CREADO_POR,@SOF_FECHA_CREACION
			)
	
	End
	Else
	Begin
		Update SOF_SOLICITUD_INF_FINANCIERA Set SOF_CONCEPTO_SALARIO=@SOF_CONCEPTO_SALARIO, 
										        SOF_VALOR_CONCEPTO_SALARIO=@SOF_VALOR_CONCEPTO_SALARIO, 
										        SOF_CONCEPTO_1=@SOF_CONCEPTO_1,SOF_VALOR_CONCEPTO_1=@SOF_VALOR_CONCEPTO_1,
												SOF_CONCEPTO_2=@SOF_CONCEPTO_2,SOF_VALOR_CONCEPTO_2=@SOF_VALOR_CONCEPTO_2, 
										        SOF_CONCEPTO_3=@SOF_CONCEPTO_3,SOF_VALOR_CONCEPTO_3=@SOF_VALOR_CONCEPTO_3,
												SOF_CONCEPTO_4=@SOF_CONCEPTO_4,SOF_VALOR_CONCEPTO_4=@SOF_VALOR_CONCEPTO_4, 
										        SOF_CONCEPTO_5=@SOF_CONCEPTO_5,SOF_VALOR_CONCEPTO_5=@SOF_VALOR_CONCEPTO_5,
												SOF_CONCEPTO_6=@SOF_CONCEPTO_6,SOF_VALOR_CONCEPTO_6=@SOF_VALOR_CONCEPTO_6, 
												SOF_VALOR_TOTAL_INGRESOS=@SOF_VALOR_TOTAL_INGRESOS, 
												SOF_VALOR_TOTAL_EGRESOS=@SOF_VALOR_TOTAL_EGRESOS,
											    SOF_ACTUALIZADO_POR=@SOF_CREADO_POR, SOF_FECHA_ACTUALIZA = @SOF_FECHA_CREACION
        Where SOC_ID = @SOC_ID

	End
	-- Retorno los Datos Financieros
	Select  * From SOF_SOLICITUD_INF_FINANCIERA
	 Where SOC_ID = @SOC_ID
END
