/*
Nombre: ObtenerSolicCreditoBasica
Descripcion: COnsulta los datos de la solicitud de Credito de la informacion basica
Elaboro: German Eduardo Guarnizo
Fecha: Abril 10 de 2021
*/
CREATE PROC[dbo].[ObtenerSolicCreditoBasica]
@SOB_ID uniqueidentifier,
@SOC_ID uniqueidentifier,
@IND int -- Indicaodr de consulta 1=SOB_ID 2 = SOC_ID

AS
Begin
	Select BS.*, DPE.DPD_NOMBRE as DEPARTAMENTO_EXPEDICION, CIE.DPC_NOMBRE as CIUDAD_EXPEDICION,
		  DPN.DPD_NOMBRE as DEPARTAMENTO_NACIMIENTO, CIN.DPC_NOMBRE as CIUDAD_NACIMIENTO,
		  FR.FRZ_DESCRIPCION as FUERZA, CT.CTG_DESCRIPCION as CATEGORIA, GR.GRD_DESCRIPCION as GRADO,
		  SX.CVL_DESCRIPCION as SEXO, NE.CVL_DESCRIPCION as NIVEL_EDUCATIVO, EC.CVL_DESCRIPCION as ESTADO_CIVIL,
		  PRF.PRF_DESCRIPCION as PROFESION
	  From SOB_SOLICITUD_INF_BASICA BS With(NoLock), 
	       DPD_DEPARTAMENTO DPE With(NoLock), DPC_CIUDAD CIE With(NoLock),
	       DPD_DEPARTAMENTO DPN With(NoLock), DPC_CIUDAD CIN With(NoLock),
		   FRZ_FUERZA FR With(NoLock), CTG_CATEGORIA CT With(NoLock), GRD_GRADO GR With(NoLock), 
		   CVL_CATALOGO_VALOR SX With(NoLock), CVL_CATALOGO_VALOR EC With(NoLock),
		   CVL_CATALOGO_VALOR NE With(NoLock), PRF_PROFESION PRF With(NoLock)
	 Where BS.DPD_ID_EXP = DPE.DPD_ID And BS.DPD_ID_EXP = CIE.DPD_ID And BS.DPC_ID_EXP = CIE.DPC_ID
	   And BS.DPD_ID_NACIMIENTO = DPN.DPD_ID And BS.DPD_ID_NACIMIENTO = CIN.DPD_ID And BS.DPC_ID_NACIMIENTO = CIN.DPC_ID
	   And BS.FRZ_ID= FR.FRZ_ID And BS.CTG_ID= CT.CTG_ID And BS.GRD_ID= GR.GRD_ID
	   And BS.SOB_SEXO = SX.CVL_CODIGO And SX.CAT_ID= 1
	   And BS.SOB_ESTADO_CIVIL = EC.CVL_CODIGO And EC.CAT_ID= 2
	   And BS.SOB_NIVEL_EDUCACION = NE.CVL_CODIGO And NE.CAT_ID= 65
	   And BS.PRF_ID= PRF.PRF_ID
	   And (
			   @IND = 1 And SOB_ID = @SOB_ID

			OR @IND = 2 And SOC_ID = @SOC_ID
		   )
End