/*
Nombre: ObtenerTramiteSolicitud
Descripcion: Consulta las Solicitudes en Tramite por usuario
Elaboro: German Eduardo Guarnizo
Fecha: Abril 20 de 2021
*/
CREATE PROC [dbo].[ObtenerTramiteSolicitud]
@FECHA_SOL varchar(10)=NULL,
@CLI_IDENTIFICACION varchar(30)=NULL,
@USUARIO_ID uniqueidentifier,
@ESTADO_ACT int=0,
@TCR_ID int=0

AS
Begin
If @FECHA_SOL IS NULL
  SET @FECHA_SOL='0'
If @CLI_IDENTIFICACION IS NULL
  SET @CLI_IDENTIFICACION='0'

Select TP.TCR_DESCRIPCION as TIPO_CREDITO, SL.SOC_FECHA_SOLICITUD FECHA_SOLICITUD, 
       SL.SOC_NUMERO_SOLICITUD as NUMERO_SOLICITUD,
       SL.CLI_IDENTIFICACION as CEDULA_CLIENTE, 
	   BAS.SOB_PRIMER_NOMBRE+' '+BAS.SOB_SEGUNDO_NOMBRE+' '+BAS.SOB_PRIMER_APELLIDO+' '+BAS.SOB_SEGUNDO_APELLIDO as NOMBRE_CLIENTE,
       TAC.TAC_DESCRIPCION as ACTIVIDAD, AFL.AFL_ORDEN as ORDEN, ESA_DESCRIPCION AS ESTADO_ACTIVIDAD,
	   ---------------------------------------------------------------------------------------
	   --- Campos ocultos
	   ---------------------------------------------------------------------------------------
	   -- Datos Solicitud
	   SL.SOC_ID as ID_SOLICITUD, SL.SLS_ID  as ID_SIMULACION, 
	   ATF.AFL_ID as ID_ACTIVIDAD_FLUJO, TRM.TRS_ID as ID_TRAMITE,
	   ATF.ACT_ESTADO AS ID_ESTADO_ACTIVIDAD, ATF.ID_USERS as USUARIO_RESPONSABLE,
	   SL.TCR_ID as ID_TIPO_CREDITO, SL.SOC_CONVENIO_ASEGURADORA as CONVENIO_ASEGURADORA,
	   SL.ASE_ID as CODIGO_ASEGURADORA, 
	   0 AS ASEGURADORA, --ASG.ASE_RAZON_SOCIAL as ASEGURADORA,
	   -- Datos Basicos
	   BAS.SOB_CELULAR as NO_CELULAR, BAS.SOB_CORREO_PERSONAL as CORREO_PERSONAL, 
	   BAS.SOB_DIRECCION_RESIDENCIA as DIRECCION_RESIDENCIA, BAS.SOB_TELEFONO_RESIDENCIA as TELEFONO_RESIDENCIA,
	   -- Datos Producto
	   PRD.SOP_TIPO_INMUEBLE as TIPO_INMUEBLE,  TV.TVV_DESCRIPCION AS TIPO_VIVIENDA,
	   PRD.SOP_VALOR_INMUEBLE as VALOR_INMUEBLE, PRD.SOP_VALOR_CREDITO as VALOR_CREDITO, 
	   PRD.SOP_PLAZO_FINANCIACION as PLAZO_FINANCIEACION, PRD.SOP_PORC_FINANCIACION as PORC_FINANCIACION,
	   -- Parametros Actividad
	   AFL.AFL_CAPTURA_DATOS_TEC AS CAPTURA_DATOS, AFL.AFL_ACTIVIDAD_PRINCIPAL AS ACTIVIDAD_PRINCIPAL,
	   AFL.AFL_CARGA_ARCHIVOS AS CARGA_ARCHIVO, AFL.AFL_VISUALIZA_ARCHIVOS AS VISUALIZA_ARCHIVOS,
	   AFL.AFL_PUEDE_DELEGAR AS PUEDE_DELEGAR, AFL.AFL_ENVIO_NOTIFICACION AS ENVIO_NITICACION, 
	   AFL.AFL_ENVIO_NOTIFICACION_VENC AS ENVIO_NOTICIACION_VENC, 
	   -- Color Grilla
	   CL.CLG_ESTILO_COLOR as COLOR_GRILLA,
	   '['+
	        Case When AFL.AFL_VISUALIZA_DATOS_BAS = 'S' Then 'DatosBasicos' Else '' End+
	        Case When AFL.AFL_VIISUALIZA_DATOS_GAR = 'S' Then ',DatosGarantia' Else '' End+
	        Case When AFL.AFL_VISUALIZA_DATOS_FIN = 'S' Then ',DatosFinancieros' Else '' End+
	        Case When AFL.AFL_VISUALIZA_ARCHIVOS = 'S' Then ',VisualizaArchivos' Else '' End+
	        Case When AFL.AFL_CARGA_ARCHIVOS = 'S' Then ',CargaArchivos' Else '' End+
	        Case When AFL.AFL_CAPTURA_DATOS_TEC = 'S' Then ',AnalisisTecnico,AnalisisJuridico' Else '' End+
	        Case When AFL.AFL_CAPTURA_DATOS_JUR = 'S' Then ',AnalisisJuridico' Else '' End+
	        Case When AFL.AFL_CAPTURA_DATOS_FIN = 'S' Then ',AnalisisFinanciero' Else '' End+
	     ',VisualizaObservaciones]' as PANELES
  From SOC_SOLICITUD_CREDITO SL With(NoLock) LEFT JOIN ASE_ASEGURADORAS ASG ON ASG.ASE_ID = SL.ASE_ID, 
       SOB_SOLICITUD_INF_BASICA BAS With(NoLock), 
       SOP_SOLICITUD_PRODUCTO PRD With(NoLock), TVV_TIPO_VIVIENDA TV With(NoLock),
       TCR_TIPO_CREDITO TP With(NoLock), ESA_ESTADO_ACTIVIDAD ESA With(NoLock),
       TRS_TRAMITE_SOLICITUD TRM With(NoLock), ACT_ACTIVIDAD_TRAMITE_SOLIC ATF With(NoLock),  
	   USR_USERS USR With(NoLock), RL_ROL RL With(NoLock),
	   AFL_ACTIVIDAD_FLUJO AFL With(NoLock), TAC_TIPO_ACTIVIDAD TAC With(NoLock),
	   CLG_COLOR_GRILLA CL With(NoLock)
Where SL.TCR_ID = TP.TCR_ID
  AND SL.SOC_ID = TRM.SOC_ID
  AND SL.SOC_ID = BAS.SOC_ID
  AND SL.SOC_ID = PRD.SOC_ID
  AND PRD.TVV_ID = TV.TVV_ID
  AND TRM.TRS_ID = ATF.TRS_ID
  AND ATF.AFL_ID = AFL.AFL_ID
  AND AFL.TAC_ID = TAC.TAC_ID
  AND ATF.ACT_ESTADO = ESA.ESA_ID
  AND ATF.ID_USERS = @USUARIO_ID
  AND ATF.ID_USERS = USR.USR_ID
  AND USR.ROLID = RL.RL_ID
  AND CL.CLG_ID = 1
  AND (@TCR_ID = 0 OR SL.TCR_ID = @TCR_ID)
  AND (@ESTADO_ACT = 0 OR ATF.ACT_ESTADO = @ESTADO_ACT)
  AND (@CLI_IDENTIFICACION = '0' OR SL.CLI_IDENTIFICACION = @CLI_IDENTIFICACION)
  AND (@FECHA_SOL = '0' OR convert(varchar(10),SL.SOC_FECHA_SOLICITUD,111) = @FECHA_SOL)
   Order by ATF.ACT_FECHA_CREACION
End
