USE [GA2]
GO
/****** Object:  StoredProcedure [dbo].[ObtenerDatosSolicComite]    Script Date: 6/07/2021 4:34:01 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
Nombre: ObtenerDatosSolicComite
Descripcion: Consulta los datos para el Pdf del Comite de la Solicitud
Elaboro: German Eduardo Guarnizo
Fecha: Mayo 07 de 2021
*/
ALTER PROC [dbo].[ObtenerDatosSolicComite]
@SOC_ID uniqueidentifier

AS
Begin
	Declare @AvalCat float
	Declare @Metros int
	Declare @Matricula varchar(20)


	Select @Metros=sum(SJI_AREA_PRIVADA), @AvalCat=sum(SJI_VALOR_AVALUO_CATASTRAL), @Matricula = MAX(SJI_NUMERO_MATRICULA) 
	  From SJI_SOLICITUD_INF_JUR_INM
	Where SOC_ID = @SOC_ID

	If @AvalCat IS NULL
	  Set @AvalCat = 0
	If @Metros IS NULL
	  Set @Metros = 0
	If @Matricula IS NULL
	  Set @Matricula = ' '



	Select Top 1 SOC.SOC_NUMERO_SOLICITUD, BS.*, EC.CVL_DESCRIPCION as ESTADO_CIVIL,
	       SOF.SOF_VALOR_CONCEPTO_1 as SALARIO_BASICO, 
	       SOF.SOF_VALOR_TOTAL_INGRESOS as TOTAL_INGRESOS, 
		   SOF.SOF_VALOR_TOTAL_EGRESOS as TOTAL_EGRESOS,
	       DPR.DPD_NOMBRE as DEPARTAMENTO_RESIDENCIA, CIR.DPC_NOMBRE as CIUDAD_RESIDENCIA, 
	       DPI.DPD_NOMBRE as DEPARTAMENTO_INMIUEBLE, CII.DPC_NOMBRE as CIUDAD_INMUEBLE,
		   SOP.SOP_DIRECCION_INMUEBLE, 
	       DPT.DPD_NOMBRE as DEPARTAMENTO_OFICINA, CIT.DPC_NOMBRE as CIUDAD_OFICINA,
		   FR.FRZ_DESCRIPCION as FUERZA, CT.CTG_DESCRIPCION as CATEGORIA, GR.GRD_DESCRIPCION as GRADO,
		   SOC.SOC_DECISION_BURO, SOC.SOC_SCORE, SOC.SOC_CAPACIDAD_ENDEUDAMIENTO, 
		   SOC.SOC_NIVEL_ENDEUDAMIENTO, SOC.SOC_NIVEL_ENDEUDAMIENTO_CUOTA,
		   DATEDIFF(year,BS.SOB_FECHA_NACIMIENTO,GETDATE()) as EDAD,
		   TV.TVV_DESCRIPCION as TIPO_VIVIENDA, 
		   SOP.SOP_TIPO_INMUEBLE as NOMBRE_VIVIENDA, 
		   SIJ.SIJ_TIPO_PARQUEADERO AS TIPO_PARQUEADERO,
		   SOP.SOP_AÑOS_CONSTRUCCION as ANO_CONSTRUCCION,
		   SIT.SIT_CONCEPTO_EST_TECNICO, 
		   SIJ.SIJ_CONCEPTO_EST_JURIDICO,
		   SIT.SIT_VALOR_AVALUO_COMERCIAL, 
		   @AvalCat as SIT_VALOR_AVALUO_CATASTRAL,
		   SIT.SIT_VALOR_VENTA_INMUEBLE,
		   @Metros as SIT_METROS_CUADRADOS,
		   round(SIT.SIT_VALOR_VENTA_INMUEBLE / @Metros,0) as SIT_VALOR_METRO_CUADRADO,
		   SIT.SIT_ESTRATO,
		   SIJ.SIJ_EDAD_JURIDICA,
		   SIJ.SIJ_CONCEPTO_JURIDICO_FIN,
		   SOP.SOP_PORC_FINANCIACION, SOP.SOP_PLAZO_FINANCIACION, SOP.SOP_PLAZO_FINANCIACION/12 as PLAZO_ANO,
		   SOP.SOP_VALOR_CREDITO, SDP.SDP_CUOTAS as NUMERO_CUOTAS,
		   CIE.DPC_NOMBRE as CIUDAD_EXPEDICION,
		   @Matricula as MATRICULA_INMOBILIARIA,
		   SOP.SOP_TIPO_INMUEBLE+' con  parqueadero '+SIJ.SIJ_TIPO_PARQUEADERO+' ubicado en  '+SOP.SOP_DIRECCION_INMUEBLE as DETALLE_INMUEBLE,
		   Convert(varchar,year(SOC.SOC_FECHA_SOLICITUD))+Convert(varchar,month(SOC.SOC_FECHA_SOLICITUD))+convert(varchar,SOC.SOC_NUMERO_SOLICITUD) as NO_CONTRATO,
          SOP.SOP_NOMBRE_VENDEDOR,  SOP.SOP_NUMERO_DOCUMENTO_VENDEDOR,   CIV.DPC_NOMBRE as CIUDAD_VENDEDOR
	  From SOB_SOLICITUD_INF_BASICA BS With(NoLock),
	       SOC_SOLICITUD_CREDITO SOC With(NoLock) 
		      LEFT JOIN SIJ_SOLICITUD_INF_JURIDICA SIJ With(NoLock) ON SIJ.SOC_ID=SOC.SOC_ID
			  LEFT JOIN SIT_SOLICITUD_INF_TECNICA SIT With(NoLock) ON SIJ.SOC_ID=SOC.SOC_ID,
		   SOP_SOLICITUD_PRODUCTO SOP With(NoLock),
		   SOF_SOLICITUD_INF_FINANCIERA SOF With(NoLock),
	       SDP_SIMULACION_DATOS_PERSONALES SDP With(NoLock), 
		   TVV_TIPO_VIVIENDA TV With(NoLock), 
	       DPD_DEPARTAMENTO DPR With(NoLock), DPC_CIUDAD CIR With(NoLock),
	       DPD_DEPARTAMENTO DPI With(NoLock), DPC_CIUDAD CII With(NoLock),
	       DPD_DEPARTAMENTO DPT With(NoLock), DPC_CIUDAD CIT With(NoLock),
	       DPC_CIUDAD CIE With(NoLock), DPC_CIUDAD CIV With(NoLock),
		   FRZ_FUERZA FR With(NoLock), CTG_CATEGORIA CT With(NoLock), GRD_GRADO GR With(NoLock),
		   CVL_CATALOGO_VALOR EC With(NoLock)
	 Where BS.SOC_ID = @SOC_ID
	   And BS.SOC_ID = SOC.SOC_ID
	   And BS.SOC_ID = SOP.SOC_ID
	   And BS.SOC_ID = SOF.SOC_ID
	   And  SOC.SLS_ID = SDP.SLS_ID
	   And SDP.SDP_NUMERO_DOCUMENTO = BS.SOB_NUMERO_DOCUMENTO
	   And SOP.TVV_ID = TV.TVV_ID
	   And BS.DPD_ID_RESIDENCIA = DPR.DPD_ID And BS.DPD_ID_RESIDENCIA = CIR.DPD_ID And BS.DPC_ID_RESIDENCIA = CIR.DPC_ID 
	   And SOP.DPD_ID = DPI.DPD_ID And SOP.DPD_ID = CII.DPD_ID And SOP.DPC_ID = CII.DPC_ID 
	   And BS.DPD_ID_OFICINA = DPT.DPD_ID And BS.DPD_ID_OFICINA = CIT.DPD_ID And BS.DPC_ID_OFICINA = CIT.DPC_ID 
	   And BS.DPD_ID_EXP = CIE.DPD_ID And BS.DPC_ID_EXP = CIE.DPC_ID
	   And SOP.DPD_ID_VENDEDOR = CIV.DPD_ID And SOP.DPC_ID_VENDEDOR = CIV.DPC_ID
	   And BS.FRZ_ID=FR.FRZ_ID And BS.CTG_ID=CT.CTG_ID And BS.GRD_ID=GR.GRD_ID
	   And BS.SOB_ESTADO_CIVIL = EC.CVL_CODIGO And EC.CAT_ID=2
End