USE [GA2]
GO
/****** Object:  StoredProcedure [dbo].[ObtenerComiteCreditoSolicitud]    Script Date: 6/07/2021 4:30:15 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
Nombre: ObtenerComiteCreditoSolicitud
Descripcion: Consulta las solicitudes aprobadas para Comite
Elaboro: German Eduardo Guarnizo
Fecha: Mayo 19 de 2021
*/
ALTER PROC [dbo].[ObtenerComiteCreditoSolicitud]
@COC_ID bigint = 0

AS
Begin
	Select SOC.SOC_ID, SOC.SOC_NUMERO_SOLICITUD, SOC.TCR_ID, TCR.TCR_DESCRIPCION as TIPO_CREDITO,
	       SOC.CLI_IDENTIFICACION, CSO.COC_ID,
		   SOB.SOB_PRIMER_NOMBRE+' '+SOB.SOB_SEGUNDO_NOMBRE+' '+SOB.SOB_PRIMER_APELLIDO+' '+SOB.SOB_SEGUNDO_APELLIDO as NOMBRE_CLIENTE,
		   Case When CSO.COS_ID IS NULL THEN ' ' Else CSO.COS_RESULTADO End as RESULTADO,
		   Case When CSO.COS_ID IS NULL THEN 'N' Else CSO.COS_APROBADA End as APROBADA,
		   Case When CSO.COS_ID IS NULL THEN 'N' Else CSO.COS_RECHAZADA End as RECHAZADA,
		   Case When CSO.COS_ID IS NULL THEN 'No' Else 'Si' End as PROCESADA,
		   Case When CSO.COS_ID IS NULL Then SMC.SMC_VALOR_PRESTAMO Else  CSO.COS_VALOR_CREDITO End  as VALOR_CREDITO, 
		   Case When CSO.COS_ID IS NULL Then SMC.SMC_TOTAL_CUOTAS Else CSO.COS_PLAZO_CREDITO End  as PLAZO_CREDITO, 
		   Case When CSO.COS_ID IS NULL Then SMC.SMC_VALOR_TASA_EA Else CSO.COS_TEA_CREDITO End  as TEA_CREDITO, 		   
		   SMD.SMD_CUOTA_TOTAL as VALOR_CUIOTA,
		   COS_CREADO_POR as USUARIO_CREACION, COS_FECHA_CREACION as FECHA_CREACION
	From SOC_SOLICITUD_CREDITO SOC
	       LEFT JOIN COS_COMITE_SOLICITUD_CREDITO CSO With(NoLock) ON CSO.SOC_ID=SOC.SOC_ID ,
         SOB_SOLICITUD_INF_BASICA SOB With(NoLock), 
	     TCR_TIPO_CREDITO TCR With(NoLock),
		 SMC_SIMULACION_CLIENTE SMC With(NoLock), SMD_SIMULACION_DETALLE SMD With(NoLock)
   Where SOC.SOC_ID = SOB.SOC_ID
     And SOC.TCR_ID = TCR.TCR_ID
     And SOC.SOC_ESTADO = 'T'
	 And SOC.SLS_ID = SMC.SLS_ID
	 And SMC.SMC_NUMERO_PREAPROBADO!=0
	 And SMC.SMC_ID = SMD.SMC_ID
	 And SMD.SMD_CUOTA=1
	 And (COS_ID IS NULL Or CSO.COC_ID = @COC_ID )
   ORDER BY SOC.SOC_NUMERO_SOLICITUD
End