USE [GA2]
GO
/****** Object:  StoredProcedure [dbo].[ObtenerDesembolsosSolicitud]    Script Date: 6/07/2021 4:49:18 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
Nombre: ObtenerDesembolsosSolicitud
Descripcion: Consulta los desembolsos discriminados para una Solicirud
Elaboro: German Eduardo Guarnizo
Fecha: Junio 17 de 2021
*/
ALTER PROC [dbo].[ObtenerDesembolsosSolicitud]
@SID_FECHA date,
@CLI_IDENTIFICACION varchar(15)='0',
@APLICADO char(1)='0'

AS
Begin
	Select  SDE.SID_ID, SDE.SOC_ID, SOC_NUMERO_SOLICITUD as NUMERO_SOLICITUD,
	            TCR.TCR_DESCRIPCION as TIPO_CREDITO, 
				SOB.SOB_NUMERO_DOCUMENTO as DOCUMENTO_CLIENTE, 
				SOB.SOB_PRIMER_NOMBRE+' '+SOB.SOB_SEGUNDO_NOMBRE+' '+SOB.SOB_PRIMER_APELLIDO+' '+SOB.SOB_SEGUNDO_APELLIDO as NOMBRE_CLIENTE,
	            SDE.FRC_ID, FRC.FRC_DESCRIPCION as FUENTE_RECURSO,
	            SDE.SID_FECHA_DESEMBOLSO, SDE.SID_VALOR_DESEMBOLSO, SDE.SID_APLICADO as APLICADO,
				SDE.SID_FECHA_APLICACION as FECHA_APLICACION,  
				Case When USR.USR_ID IS NOT NULL Then USR.USR_USERNAME Else ' ' End as APLICADO_POR,
				SDE.SID_ANULADO as ANULADO, SDE.SID_FECHA_ANULACION as FECHA_ANULACION, 
				SDE.SID_OBSERVACION_ANULACION as OBSERVACION_ANULACION,
				Case When USR1.USR_ID IS NOT NULL Then USR1.USR_USERNAME Else ' ' End as ANULADO_POR,
				Case When CDD.CDD_ID IS NOT NULL Then CDD.CDD_DESCRIPCION Else ' ' End as CAUSA_ANULACION,
				SDe.SID_CREADO_POR as CREADO_POR,  SDE.SID_FECHA_CREACION as FECHA_CREACION, 
				SDE.SID_ACTUALIZADO_POR as ACTUALIZADO_PRO,  SDE.SID_FECHA_ACTUALIZA as FECHA_ACTUALIZACION
	  From SID_SOLICITUD_INF_DESEMBOLSO SDE With(NoLock) 
	             LEFT JOIN USR_USERS USR ON USR.USR_ID=SDE.SID_APLICADO_POR 
				 LEFT JOIN CDD_CAUSAL_DESISTIMIENTO_DES CDD With(NoLock) ON CDD.CDD_ID=SDE.CDD_ID
				 LEFT JOIN USR_USERS USR1 ON USR1.USR_ID=SDE.SID_ANULADO_POR ,
	           SOC_SOLICITUD_CREDITO SOC With(NoLock),  SOB_SOLICITUD_INF_BASICA SOB With(NoLock), 
              TCR_TIPO_CREDITO TCR With(NoLock), FRC_FUENTES_RECURSOS FRC With(NoLock)
  Where SDE.SOC_ID = SOC.SOC_ID
      And SOC.SOC_ID=SOB.SOC_ID
	  And SOC.TCR_ID=TCR.TCR_ID
	  And SDE.FRC_ID=FRC.FRC_ID
	  And SDE.SID_FECHA_DESEMBOLSO = @SID_FECHA
	  And (@APLICADO = '0' Or SDE.SID_APLICADO = @APLICADO)
	  And (@CLI_IDENTIFICACION = '0' Or SOB.SOB_NUMERO_DOCUMENTO = @CLI_IDENTIFICACION)
	 Order by SOC.SOC_NUMERO_SOLICITUD

End
