/*
Nombre: ActualizarEstado
Descripcion: Actualiza el estado por el ID
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/
CREATE PROCEDURE[dbo].ActualizarEstado
@ID int,
@CODIGO int,
@CONCEPTO nvarchar(25),
@DIASMORAACTIVAESTADO nvarchar(25),
@SALDODEUDA nvarchar(25),
@FECHAMODIFICACION datetime,
@MODIFICADOPOR int,
@ESTADO bit
AS 
BEGIN
UPDATE GA2..MOD_ESTADO
SET EST_CODIGO = @CODIGO,
EST_CONCEPTO = @CONCEPTO,
EST_DIAS_MORA_ACTIVA_ESTADO = @DIASMORAACTIVAESTADO,
EST_SALDO_DEUDA = @SALDODEUDA,
EST_FECHA_MODIFICACION = @FECHAMODIFICACION,
EST_MODIFICADO_POR = @MODIFICADOPOR,
EST_ESTADO = @ESTADO
WHERE EST_ID = @ID
END
