/*
Nombre: CrearEstado
Descripcion: Crear el estado
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/
CREATE PROCEDURE[dbo].CrearEstado
@ID int,
@CODIGO int,
@CONCEPTO nvarchar(25),
@DIASMORAACTIVAESTADO nvarchar(25),
@SALDODEUDA nvarchar(25),
@FECHAMODIFICACION datetime,
@MODIFICADOPOR int,
@ESTADO bit
AS 
BEGIN
INSERT INTO GA2..MOD_ESTADO
(EST_CODIGO,
EST_CONCEPTO,
EST_DIAS_MORA_ACTIVA_ESTADO,
EST_SALDO_DEUDA,
EST_FECHA_MODIFICACION,
EST_MODIFICADO_POR,
EST_ESTADO) 
VALUES(@CODIGO,
@CONCEPTO,
@DIASMORAACTIVAESTADO,
@SALDODEUDA,
@FECHAMODIFICACION,
@MODIFICADOPOR,
@ESTADO)
END

