------------------------------------------
-- auhtor Camilo Andres Yaya Poveda
-- descripcion: Tabla para los productos
-- date: 07 / 05 / 2021
------------------------------------------
IF OBJECT_ID('GA2.dbo.PRD_PRODUCTO') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.PRD_PRODUCTO;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.PRD_PRODUCTO (
	PRD_NUMERO_CREDITO int NOT NULL,
	TCR_ID int NOT NULL,
	PRD_FECHA_ALTA date NOT NULL,
	PRD_ESTADO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRD_FECHA_ESTADO date NOT NULL,
	PRD_FECHA_PAGO date NOT NULL,
	PRD_DIAS_MORA int NOT NULL,
	PRD_VALOR int NOT NULL,
	TIV_VIVIENDA_ID int NOT NULL,
	ESV_ESTADO_VIVIENDA int NOT NULL,
	PRD_CREDITO int NOT NULL,
	PRD_DEUDA int NOT NULL,
	PRD_MORA int NOT NULL,
	PRD_CUOTA_ANO int NOT NULL,
	PRD_CUOTA_MES int NOT NULL,
	PRD_SEGURO_VIDA decimal(4,2) NOT NULL,
	PRD_SEGURO_TODO_RIESGO decimal(4,2) NOT NULL,
	PRD_TASA_EFECTIVA_ANUAL decimal(4,2) NOT NULL,
	PRD_TASA_NOMINAL_MENSUAL decimal(4,2) NOT NULL,
	PRD_TASA_FRECH_APLICA bit NOT NULL,
	PRD_TASA_FRECH decimal(4,2) NOT NULL,
	PRD_ALIVIO_COUTA_APLICA bit NOT NULL,
	PRD_ALIVIO_CUOTA int NOT NULL,
	CONSTRAINT PK_PRD_PRODUCTO PRIMARY KEY (PRD_NUMERO_CREDITO)
);
END