IF OBJECT_ID ('ActualizarSolicitudTarea', 'P') > 0
BEGIN
	DROP PROCEDURE ActualizarSolicitudTarea
END
GO
CREATE PROCEDURE ActualizarSolicitudTarea 
	@SLT_ID					UNIQUEIDENTIFIER,
	@SLT_ESTADO_SOLICITUD	INT
AS
BEGIN
	UPDATE SLT_SOLICITUD_TAREA
	SET SLT_ESTADO_SOLICITUD = @SLT_ESTADO_SOLICITUD
	WHERE SLT_ID = @SLT_ID
 
END