IF OBJECT_ID('ActualizarSolicitud', 'P') > 0
BEGIN
	DROP PROCEDURE ActualizarSolicitud
END
GO
CREATE PROCEDURE ActualizarSolicitud
	@SOL_ID_FK					UNIQUEIDENTIFIER,
	@SOL_VALOR_A_RETIRAR		DECIMAL(18,2)
AS
BEGIN
	UPDATE SOL_SOLICITUD
	SET SOL_VALOR_A_RETIRAR = @SOL_VALOR_A_RETIRAR
	WHERE SOL_ID = @SOL_ID_FK
END