
IF OBJECT_ID('ConsultarTerceroApoderado', 'P') > 0
BEGIN
	DROP PROCEDURE ConsultarTerceroApoderado
END
GO
CREATE PROCEDURE ConsultarTerceroApoderado
	@SOL_ID_FK				UNIQUEIDENTIFIER,
	@TER_TIPO_TERCERO_FK	INT
AS
BEGIN
	SELECT 
		TER_TERCERO.TER_ID, TER_TERCERO.TID_ID_FK, TID_TIPO_IDENTIFICACION.TID_DESCRIPCION, TER_TERCERO.TER_NUMERO_DOCUMENTO, 
		TER_TERCERO.TER_NOMBRE_RAZON_SOCIAL, CVL_CATALOGO_VALOR.CVL_ID, CVL_CATALOGO_VALOR.CVL_DESCRIPCION, TER_TERCERO.TER_ESAUTORIZADO
	FROM TER_TERCERO 
		INNER JOIN TID_TIPO_IDENTIFICACION ON TER_TERCERO.TID_ID_FK = TID_TIPO_IDENTIFICACION.TID_ID
		LEFT JOIN CVL_CATALOGO_VALOR ON TER_TERCERO.TER_PARENTESCO = CVL_CATALOGO_VALOR.CVL_ID
	WHERE SOL_ID_FK = @SOL_ID_FK AND TER_TIPO_TERCERO_FK = @TER_TIPO_TERCERO_FK
END