IF OBJECT_ID ('ConsultarExisteSolicitud', 'P') > 0
BEGIN
	DROP PROCEDURE ConsultarExisteSolicitud
END
GO
CREATE PROCEDURE ConsultarExisteSolicitud
	@CLI_ID					INT,
	@TPS_SUB_ID				UNIQUEIDENTIFIER,
	@SOL_ESTADO_ANULADO		INT
AS
BEGIN
	SELECT TOP 1
		SOL_SOLICITUD.SOL_ID,
		SLT_SOLICITUD_TAREA.SLT_ID,
		SOL_SOLICITUD.CTA_ID,
		SOL_SOLICITUD.TPS_SUB_ID,
		SOL_SOLICITUD.CLI_ID,
		SOL_SOLICITUD.SOL_FECHA_SOLICITUD,
		SOL_SOLICITUD.SOL_ESTADO,
		SLT_SOLICITUD_TAREA.SLT_ESTADO_SOLICITUD,
		CASE WHEN SLT_SOLICITUD_TAREA.SLT_ESTADO_SOLICITUD IN (327, 329) THEN TIM_TIPO_MODALIDAD.TIM_CODIGO ELSE '' END AS VOLVER_PANTALLA,
		TPS_TIPO_SUBMODALIDAD.TPS_SUB_DESCRIPCION,
		TIM_TIPO_MODALIDAD.TIM_DESCRIPCION,
		UPPER(PSC_PROCESO.PCS_DESCRIPCION) AS PCS_DESCRIPCION,
		SOL_VALOR_A_RETIRAR
	FROM SOL_SOLICITUD
	INNER JOIN SLT_SOLICITUD_TAREA ON SOL_SOLICITUD.SOL_ID = SLT_SOLICITUD_TAREA.SOL_ID
	INNER JOIN TPS_TIPO_SUBMODALIDAD ON SOL_SOLICITUD.TPS_SUB_ID = TPS_TIPO_SUBMODALIDAD.TPS_SUB_ID
	INNER JOIN TIM_TIPO_MODALIDAD ON TPS_TIPO_SUBMODALIDAD.TIM_ID = TIM_TIPO_MODALIDAD.TIM_ID
	INNER JOIN PSC_PROCESO ON TIM_TIPO_MODALIDAD.PCS_ID = PSC_PROCESO.PCS_ID
	WHERE SOL_SOLICITUD.CLI_ID = @CLI_ID 
	AND SOL_SOLICITUD.TPS_SUB_ID = @TPS_SUB_ID
	AND SOL_SOLICITUD.SOL_ESTADO_SOLICITUD != @SOL_ESTADO_ANULADO
	ORDER BY SLT_SOLICITUD_TAREA.SLT_FECHACREACION ASC
END