
IF OBJECT_ID('ConsultarSolicitudPropietario', 'P') > 0
BEGIN
	DROP PROCEDURE ConsultarSolicitudPropietario
END
GO
CREATE PROCEDURE ConsultarSolicitudPropietario
	@SOL_ID				UNIQUEIDENTIFIER
AS
BEGIN
	SELECT 
		PRP_PROPIETARIO.PRP_ID,
		PRP_PROPIETARIO.SOL_ID_FK,
		PRP_NUMERO_IDENTIFICACION,
		PRP_NOMBRE_RAZON_SOCIAL,
		TID_ID_FK,
		TID_TIPO_IDENTIFICACION.TID_DESCRIPCION,
		PRP_ESTADO,
		PRP_CREATEDOPOR,
		PRP_FECHACREACION,
		PRP_MODIFICADOPOR,
		PRP_FECHAMODIFICACION,
		MAI_MATRICULA_INMOBILIARIA.MAI_ID,
		MAI_MATRICULA_INMOBILIARIA.MAI_NUMERO_MATRICULA,
		MAI_MATRICULA_INMOBILIARIA.MAI_PRINCIPAL
	FROM PRP_PROPIETARIO 
		INNER JOIN TID_TIPO_IDENTIFICACION ON PRP_PROPIETARIO.TID_ID_FK = TID_TIPO_IDENTIFICACION.TID_ID
		INNER JOIN PMA_PROPIETARIO_MATRICULA ON PRP_PROPIETARIO.PRP_ID = PMA_PROPIETARIO_MATRICULA.PRP_ID
		INNER JOIN MAI_MATRICULA_INMOBILIARIA ON PMA_PROPIETARIO_MATRICULA.MAI_ID = MAI_MATRICULA_INMOBILIARIA.MAI_ID
	WHERE PRP_PROPIETARIO.SOL_ID_FK = @SOL_ID
END