IF OBJECT_ID('ConsultarSolicitudMatricula', 'P') > 0
BEGIN
	DROP PROCEDURE ConsultarSolicitudMatricula
END
GO
CREATE PROCEDURE ConsultarSolicitudMatricula
	@SOL_ID				UNIQUEIDENTIFIER
AS
BEGIN
	SELECT 
		SOL_ID_FK, MAI_NUMERO_MATRICULA, MAI_FECHA_REGISTRO, MAI_DIRECCION, DPC_ID_FK, DPC_NOMBRE, DPD_DEPARTAMENTO.DPD_ID, 
		DPD_DEPARTAMENTO.DPD_NOMBRE, MAI_PRINCIPAL, MAI_ID
	FROM MAI_MATRICULA_INMOBILIARIA
		INNER JOIN DPC_CIUDAD ON DPC_ID = DPC_ID_FK
		INNER JOIN DPD_DEPARTAMENTO ON DPD_DEPARTAMENTO.DPD_ID = DPC_CIUDAD.DPD_ID
	WHERE SOL_ID_FK = @SOL_ID
END