
IF OBJECT_ID('ConsultarTerceroVendedor', 'P') > 0
BEGIN
	DROP PROCEDURE ConsultarTerceroVendedor
END
GO
CREATE PROCEDURE ConsultarTerceroVendedor
	@SOL_ID_FK				UNIQUEIDENTIFIER,
	@TER_TIPO_TERCERO_FK	INT
AS
BEGIN
	SELECT 
		TER_TERCERO.TER_ID, TER_TERCERO.TID_ID_FK, TID_TIPO_IDENTIFICACION.TID_DESCRIPCION, TER_TERCERO.TER_NUMERO_DOCUMENTO, 
		TER_TERCERO.TER_NOMBRE_RAZON_SOCIAL, TER_TERCERO.TER_DIRECCION, DPD_DEPARTAMENTO.DPD_ID, DPD_DEPARTAMENTO.DPD_NOMBRE,
		DPC_CIUDAD.DPC_ID, DPC_CIUDAD.DPC_NOMBRE, TER_TERCERO.TER_CORREO_ELECTRONICO, TER_TERCERO.TER_TELEFONO
	FROM TER_TERCERO 
		INNER JOIN DPC_CIUDAD ON TER_TERCERO.DPC_ID_FK = DPC_CIUDAD.DPC_ID
		INNER JOIN DPD_DEPARTAMENTO ON DPC_CIUDAD.DPD_ID = DPD_DEPARTAMENTO.DPD_ID
		INNER JOIN TID_TIPO_IDENTIFICACION ON TER_TERCERO.TID_ID_FK = TID_TIPO_IDENTIFICACION.TID_ID
	WHERE SOL_ID_FK = @SOL_ID_FK AND TER_TIPO_TERCERO_FK = @TER_TIPO_TERCERO_FK
END