
IF OBJECT_ID('ConsultarTerceroEntidadEducativa', 'P') > 0
BEGIN
	DROP PROCEDURE ConsultarTerceroEntidadEducativa
END
GO
CREATE PROCEDURE ConsultarTerceroEntidadEducativa
	@SOL_ID_FK				UNIQUEIDENTIFIER,
	@TER_TIPO_TERCERO_FK	INT
AS
BEGIN
	SELECT ENE_ID_FK, TER_NUMERO_DOCUMENTO, TER_NOMBRE_RAZON_SOCIAL, PGN_ID, PRN_ID, TER_NUM_RECIBO_PAGO, CONVERT(VARCHAR,TER_FECHA_LIMITE_PAGO ,101) AS TER_FECHA_LIMITE_PAGO
	FROM TER_TERCERO
		INNER JOIN PGN_PROGRAMA_ENTIDAD ON TER_TERCERO.PGN_ID_FK = PGN_PROGRAMA_ENTIDAD.PGN_ID
		INNER JOIN PRN_PROGRAMA_NIVEL ON PGN_PROGRAMA_ENTIDAD.PGN_ID = PRN_PROGRAMA_NIVEL.PGN_ID_FK
	WHERE SOL_ID_FK = @SOL_ID_FK AND TER_TIPO_TERCERO_FK = @TER_TIPO_TERCERO_FK
END