IF OBJECT_ID('InsertarSolicitudPropietario', 'P')>0
BEGIN
	DROP PROCEDURE InsertarSolicitudPropietario
END
GO
CREATE PROCEDURE InsertarSolicitudPropietario
	@NUMERO_IDENTIFICACION	VARCHAR(50),
	@NOMBRE_RAZON_SOCIAL	VARCHAR(100),
	@TID_ID_FK				INT,
	@PRP_CREATEDOPOR		UNIQUEIDENTIFIER,
	@SOL_ID_FK				UNIQUEIDENTIFIER
AS
BEGIN

	DECLARE @ID UNIQUEIDENTIFIER
	SET @ID = NEWID()
	
	INSERT INTO PRP_PROPIETARIO
	(
		PRP_ID,
		SOL_ID_FK,
		PRP_NUMERO_IDENTIFICACION,
		PRP_NOMBRE_RAZON_SOCIAL,
		TID_ID_FK,
		PRP_ESTADO,
		PRP_FECHACREACION,
		PRP_CREATEDOPOR
	) 
	VALUES (
		@ID,
		@SOL_ID_FK,
		@NUMERO_IDENTIFICACION,
		@NOMBRE_RAZON_SOCIAL,
		@TID_ID_FK,
		1,
		GETDATE(),
		@PRP_CREATEDOPOR
	)

	SELECT
		@ID AS PRP_ID,
		@SOL_ID_FK AS SOL_ID_FK,
		@NUMERO_IDENTIFICACION AS PRP_NUMERO_IDENTIFICACION, 
		@NOMBRE_RAZON_SOCIAL AS PRP_NOMBRE_RAZON_SOCIAL, 
		@TID_ID_FK AS TID_ID_FK
	FROM PRP_PROPIETARIO WHERE PRP_ID = @ID
END