IF OBJECT_ID('InsertarSolicitudTerceroVendedor', 'P')>0
BEGIN
	DROP PROCEDURE InsertarSolicitudTerceroVendedor
END
GO
CREATE PROCEDURE InsertarSolicitudTerceroVendedor
	@SOL_ID_FK						UNIQUEIDENTIFIER,
	@TID_ID_FK						INT,
	@TER_TIPO_TERCERO_FK			INT = NULL,
	@NUMERO_DOCUMENTO				VARCHAR(16),
	@NOMBRE_RAZON_SOCIAL			VARCHAR(100),
	@DIRECCION						VARCHAR(100),
	@DPC_ID_FK						INT,
	@CORREO_ELECTRONICO				VARCHAR(50),
	@TELEFONO						VARCHAR(20),
	@TER_CREATEDOPOR				UNIQUEIDENTIFIER
AS
BEGIN

	DECLARE @ID UNIQUEIDENTIFIER
	SET @ID = NEWID()
	
	INSERT INTO TER_TERCERO
	(
		TER_ID,
		TER_TIPO_TERCERO_FK,
		SOL_ID_FK,
		TID_ID_FK,
		TER_NUMERO_DOCUMENTO,
		TER_NOMBRE_RAZON_SOCIAL,
		TER_DIRECCION,
		DPC_ID_FK,
		TER_CORREO_ELECTRONICO,
		TER_TELEFONO,
		TER_ESTADO,
		TER_CREATEDOPOR,
		TER_FECHACREACION
	) 
	VALUES (
		@ID,
		@TER_TIPO_TERCERO_FK,
		@SOL_ID_FK,
		@TID_ID_FK,
		@NUMERO_DOCUMENTO,
		@NOMBRE_RAZON_SOCIAL,
		@DIRECCION,
		@DPC_ID_FK,
		@CORREO_ELECTRONICO,
		@TELEFONO,
		1,
		@TER_CREATEDOPOR,
		GETDATE()
	)

	SELECT
		@ID AS TER_ID,
		@SOL_ID_FK AS SOL_ID_FK,
		@TID_ID_FK AS TID_ID_FK,
		@NUMERO_DOCUMENTO AS TER_NUMERO_DOCUMENTO, 
		@NOMBRE_RAZON_SOCIAL AS TER_NOMBRE_RAZON_SOCIAL, 
		@DIRECCION AS TER_DIRECCION,
		@DPC_ID_FK AS CIUDAD,
		@CORREO_ELECTRONICO AS CORREO_ELECTRONICO,
		@TELEFONO AS TER_TELEFONO
	FROM TER_TERCERO WHERE TER_ID = @ID
END