IF OBJECT_ID('InsertarSolicitudTerceroEntidadEducativa', 'P')>0
BEGIN
	DROP PROCEDURE InsertarSolicitudTerceroEntidadEducativa
END
GO
CREATE PROCEDURE InsertarSolicitudTerceroEntidadEducativa
	@PGN_ID_FK						UNIQUEIDENTIFIER,
	@SOL_ID_FK						UNIQUEIDENTIFIER,
	@TID_ID_FK						INT,
	@TER_TIPO_TERCERO_FK			INT = NULL,
	@NUMERO_DOCUMENTO				VARCHAR(16),
	@NOMBRE_RAZON_SOCIAL			VARCHAR(100),
	@PRN_ID_FK						UNIQUEIDENTIFIER,
	@TER_NUM_RECIBO_PAGO			VARCHAR(20) NULL,
	@TER_FECHA_LIMITE_PAGO			DATETIME NULL,
	@TER_CREATEDOPOR				UNIQUEIDENTIFIER
AS
BEGIN

	DECLARE @ID UNIQUEIDENTIFIER
	SET @ID = NEWID()
	
	INSERT INTO TER_TERCERO
	(
		TER_ID,
		PGN_ID_FK,
		SOL_ID_FK,
		TID_ID_FK,
		TER_TIPO_TERCERO_FK,
		TER_NUMERO_DOCUMENTO,
		TER_NOMBRE_RAZON_SOCIAL,
		PRN_ID_FK,
		TER_NUM_RECIBO_PAGO,
		TER_FECHA_LIMITE_PAGO,
		TER_CREATEDOPOR,
		TER_ESTADO,
		TER_FECHACREACION
	) 
	VALUES (
		@ID,
		@PGN_ID_FK,
		@SOL_ID_FK,
		@TID_ID_FK,
		@TER_TIPO_TERCERO_FK,
		@NUMERO_DOCUMENTO,
		@NOMBRE_RAZON_SOCIAL,
		@PRN_ID_FK,
		@TER_NUM_RECIBO_PAGO,
		@TER_FECHA_LIMITE_PAGO,
		@TER_CREATEDOPOR,
		1,
		GETDATE()
	)

	SELECT
		@ID AS TER_ID,
		@PGN_ID_FK AS PGN_ID_FK,
		@SOL_ID_FK AS SOL_ID_FK,
		@TID_ID_FK AS TID_ID_FK, 
		@TER_TIPO_TERCERO_FK AS TER_TIPO_TERCERO_FK,
		@NUMERO_DOCUMENTO AS TER_NUMERO_DOCUMENTO,
		@NOMBRE_RAZON_SOCIAL AS TER_NOMBRE_RAZON_SOCIAL,
		@PRN_ID_FK AS PRN_ID_FK, 
		@TER_NUM_RECIBO_PAGO AS TER_NUM_RECIBO_PAGO,
		@TER_FECHA_LIMITE_PAGO AS TER_FECHA_LIMITE_PAGO
	FROM TER_TERCERO WHERE TER_ID = @ID
END