IF OBJECT_ID('InsertarSolicitudMatricula', 'P')>0
BEGIN
	DROP PROCEDURE InsertarSolicitudMatricula
END
GO
CREATE PROCEDURE InsertarSolicitudMatricula
	@SOL_ID_FK			UNIQUEIDENTIFIER,
	@NUMERO_MATRICULA	VARCHAR(50),
	@FECHA_REGISTRO		DATETIME,
	@DIRECCION			VARCHAR(100),
	@DPC_ID_FK			INT,
	@MAI_PRINCIPAL		BIT,
	@MAI_CREATEDOPOR	UNIQUEIDENTIFIER
AS
BEGIN

	DECLARE @ID			AS UNIQUEIDENTIFIER
	SET @ID = NEWID()
	
	INSERT INTO MAI_MATRICULA_INMOBILIARIA
	(
		MAI_ID,
		SOL_ID_FK,
		MAI_NUMERO_MATRICULA,
		MAI_FECHA_REGISTRO,
		MAI_DIRECCION,
		DPC_ID_FK,
		MAI_ESTADO,
		MAI_FECHACREACION,
		MAI_PRINCIPAL,
		MAI_CREATEDOPOR
	) 
	VALUES (
		@ID,
		@SOL_ID_FK,
		@NUMERO_MATRICULA,
		@FECHA_REGISTRO,
		@DIRECCION,
		@DPC_ID_FK,
		1,
		GETDATE(),
		@MAI_PRINCIPAL,
		@MAI_CREATEDOPOR
	)

	SELECT
		@ID AS MAI_ID,
		@SOL_ID_FK AS SOL_ID_FK, 
		@NUMERO_MATRICULA AS MAI_NUMERO_MATRICULA, 
		@FECHA_REGISTRO AS MAI_FECHA_REGISTRO, 
		@DIRECCION AS MAI_DIRECCION, 
		@DPC_ID_FK AS DPC_ID_FK,
		@MAI_PRINCIPAL AS MAI_PRINCIPAL
	FROM MAI_MATRICULA_INMOBILIARIA WHERE MAI_ID = @ID
END