IF OBJECT_ID('InsertarSolicitudTerceroBeneficiario', 'P')>0
BEGIN
	DROP PROCEDURE InsertarSolicitudTerceroBeneficiario
END
GO
CREATE PROCEDURE InsertarSolicitudTerceroBeneficiario
	@SOL_ID_FK					UNIQUEIDENTIFIER,
	@TID_ID_FK					INT,
	@TER_TIPO_TERCERO_FK		INT = NULL,
	@NUMERO_DOCUMENTO			VARCHAR(16),
	@NOMBRE_RAZON_SOCIAL		VARCHAR(100),
	@ENT_ID_FK					UNIQUEIDENTIFIER = NULL,
	@TER_TIPO_CUENTA_FK			INT,
	@NUMERO_CUENTA				VARCHAR(16),
	@TER_CREATEDOPOR			UNIQUEIDENTIFIER
AS
BEGIN

	DECLARE @ID UNIQUEIDENTIFIER
	SET @ID = NEWID()
	
	INSERT INTO TER_TERCERO
	(
		TER_ID,
		TER_TIPO_TERCERO_FK,
		SOL_ID_FK,
		TID_ID_FK,
		TER_NUMERO_DOCUMENTO,
		TER_NOMBRE_RAZON_SOCIAL,
		ENT_ID_FK,
		TER_TIPO_CUENTA_FK,
		TER_NUMERO_CUENTA,
		TER_ESTADO,
		TER_CREATEDOPOR,
		TER_FECHACREACION
	) 
	VALUES (
		@ID,
		@TER_TIPO_TERCERO_FK,
		@SOL_ID_FK,
		@TID_ID_FK,
		@NUMERO_DOCUMENTO,
		@NOMBRE_RAZON_SOCIAL,
		@ENT_ID_FK,
		@TER_TIPO_CUENTA_FK,
		@NUMERO_CUENTA,
		1,
		@TER_CREATEDOPOR,
		GETDATE()
	)

	SELECT
		@ID AS TER_ID,
		@SOL_ID_FK AS SOL_ID_FK,
		@TID_ID_FK AS TID_ID_FK,
		@NUMERO_DOCUMENTO AS TER_NUMERO_DOCUMENTO, 
		@NOMBRE_RAZON_SOCIAL AS TER_NOMBRE_RAZON_SOCIAL, 
		@ENT_ID_FK AS ENTIDAD_ID,
		@TER_TIPO_CUENTA_FK AS TER_TIPO_CUENTA,
		@NUMERO_CUENTA AS NUMERO_CUENTA
	FROM TER_TERCERO WHERE TER_ID = @ID
END