IF OBJECT_ID('InsertarSolicitudTerceroAutorizado', 'P')>0
BEGIN
	DROP PROCEDURE InsertarSolicitudTerceroAutorizado
END
GO
CREATE PROCEDURE InsertarSolicitudTerceroAutorizado
	@SOL_ID_FK						UNIQUEIDENTIFIER,
	@TID_ID_FK						INT,
	@NUMERO_DOCUMENTO				VARCHAR(16),
	@NOMBRE_RAZON_SOCIAL			VARCHAR(100),
	@TER_CREATEDOPOR				UNIQUEIDENTIFIER
AS
BEGIN

	DECLARE @ID UNIQUEIDENTIFIER
	SET @ID = NEWID()
	
	INSERT INTO TER_TERCERO
	(
		TER_ID,
		SOL_ID_FK,
		TID_ID_FK,
		TER_NUMERO_DOCUMENTO,
		TER_NOMBRE_RAZON_SOCIAL,
		TER_ESTADO,
		TER_CREATEDOPOR,
		TER_FECHACREACION
	) 
	VALUES (
		@ID,
		@SOL_ID_FK,
		@TID_ID_FK,
		@NUMERO_DOCUMENTO,
		@NOMBRE_RAZON_SOCIAL,
		1,
		@TER_CREATEDOPOR,
		GETDATE()
	)

	SELECT
		@ID AS TER_ID,
		@SOL_ID_FK AS SOL_ID_FK,
		@TID_ID_FK AS TID_ID_FK,
		@NUMERO_DOCUMENTO AS TER_NUMERO_DOCUMENTO, 
		@NOMBRE_RAZON_SOCIAL AS TER_NOMBRE_RAZON_SOCIAL
	FROM TER_TERCERO WHERE TER_ID = @ID
END