using System;

namespace GA2.Domain.Entities
{

    public class DatosSolicitudComite
    {
        public Guid SOB_ID { get; set; }
        public Guid SOC_ID { get; set; }
        public int TID_ID { get; set; }
        public int SOB_NUMERO_DOCUMENTO { get; set; }
        public DateTime SOB_FECHA_EXPEDICION { get; set; }
        public int DPD_ID_EXP { get; set; }
        public int DPC_ID_EXP { get; set; }
        public string SOB_PRIMER_APELLIDO { get; set; }
        public string SOB_SEGUNDO_APELLIDO { get; set; }
        public string SOB_PRIMER_NOMBRE { get; set; }
        public string SOB_SEGUNDO_NOMBRE { get; set; }
        public DateTime SOB_FECHA_NACIMIENTO { get; set; }
        public string CIUDAD_NACIMIENTO { get; set; }
        public int DPD_ID_NACIMIENTO { get; set; }
        public int DPC_ID_NACIMIENTO { get; set; }
        public string SOB_SEXO { get; set; }
        public string ESTADO_CIVIL { get; set; }
        public string SOB_NIVEL_EDUCACION { get; set; }
        public int FRZ_ID { get; set; }
        public int CTG_ID { get; set; }
        public int GRD_ID { get; set; }
        public int DPD_ID_RESIDENCIA { get; set; }
        public int DPC_ID_RESIDENCIA { get; set; }
        public string SOB_DIRECCION_RESIDENCIA { get; set; }
        public string SOB_CORREO_PERSONAL { get; set; }
        public string SOB_TELEFONO_RESIDENCIA { get; set; }
        public string SOB_CELULAR { get; set; }
        public int DPD_ID_OFICINA { get; set; }
        public int DPC_ID_OFICINA { get; set; }
        public string SOB_DIRECCION_OFICINA { get; set; }
        public string SOB_CORREO_INSTITUCIONAL { get; set; }
        public string SOB_TELEFONO_OFICINA { get; set; }
        public int ACC_ID { get; set; }
        public int PRF_ID { get; set; }
        public string SOB_TIENE_TRANSACCION_ME { get; set; }
        public string SOB_TIPO_TRANSACCION_ME { get; set; }
        public string SOB_TIPO_PRODUCTO_ME { get; set; }
        public string SOB_BANCO_TRANSACCION_ME { get; set; }
        public string SOB_NUMERO_PRODUCTO_ME { get; set; }
        public int SOB_SALDO_PROMEDIO_CUENTAS_ME { get; set; }
        public string SOB_MONEDA_TRANSACCION_ME { get; set; }
        public int DPP_ID_ME { get; set; }
        public int DPD_ID_ME { get; set; }
        public Guid SOB_CREADO_POR { get; set; }
        public DateTime SOB_FECHA_CREACION { get; set; }
        public Guid SOB_ACTUALIZADO_POR { get; set; }
        public DateTime SOB_FECHA_ACTUALIZA { get; set; }
        public int SALARIO_BASICO { get; set; }
        public int TOTAL_EGRESOS { get; set; }
        public int TOTAL_INGRESOS { get; set; }
        public string DEPARTAMENTO_RESIDENCIA { get; set; }
        public string CIUDAD_RESIDENCIA { get; set; }
        public string DEPARTAMENTO_INMIUEBLE { get; set; }
        public string CIUDAD_INMUEBLE { get; set; }
        public string SOP_DIRECCION_INMUEBLE { get; set; }
        public string DEPARTAMENTO_OFICINA { get; set; }
        public string CIUDAD_OFICINA { get; set; }
        public string FUERZA { get; set; }
        public string CATEGORIA { get; set; }
        public string PROSPECTA { get; set; }
        public string SCORE_CAJA { get; set; }
        public string SCORE_AQM { get; set; }
        public string CAPACIDAD_PAGO_AQM { get; set; }
        public string HABITO_PAGO { get; set; }
        public string GRADO { get; set; }
        public string SOC_DECISION_BURO { get; set; }
        public string SOC_SCORE { get; set; }
        public string SOC_CAPACIDAD_ENDEUDAMIENTO { get; set; }
        public string SOC_NIVEL_ENDEUDAMIENTO { get; set; }
        public string SOC_NIVEL_ENDEUDAMIENTO_CUOTA { get; set; }
        public int EDAD { get; set; }
        public string TIPO_VIVIENDA { get; set; }
        public string NOMBRE_VIVIENDA { get; set; }
        public string TIPO_PARQUEADERO { get; set; }
        public string ANO_CONSTRUCCION { get; set; }
        public string SIT_CONCEPTO_EST_TECNICO { get; set; }
        public string SIJ_CONCEPTO_EST_JURIDICO { get; set; }
        public int SIT_VALOR_AVALUO_COMERCIAL { get; set; }
        public int SIT_VALOR_VENTA_INMUEBLE { get; set; }
        public decimal SOP_PORC_FINANCIACION { get; set; }
        public int PLAZO_FINANCIACION { get; set; }
        public decimal SOP_VALOR_CREDITO { get; set; }
        public int NUMERO_CUOTAS { get; set; }
        public int SOC_NUMERO_SOLICITUD { get; set; }
        public int SIT_VALOR_AVALUO_CATASTRAL { get; set; }
        public int SIT_METROS_CUADRADOS { get; set; }
        public int SIT_VALOR_METRO_CUADRADO { get; set; }
        public string SIT_ESTRATO { get; set; }
        public string SIJ_EDAD_JURIDICA { get; set; }
        public string SIJ_CONCEPTO_JURIDICO_FIN { get; set; }
        public int PLAZO_ANO { get; set; }
        public string CIUDAD_EXPEDICION { get; set; }
        public string MATRICULA_INMOBILIARIA { get; set; }
        public string DETALLE_INMUEBLE { get; set; }
        public int NO_CONTRATO { get; set; }
        public string SOP_NOMBRE_VENDEDOR { get; set; }
        public string SOP_NUMERO_DOCUMENTO_VENDEDOR { get; set; }
        public string CIUDAD_VENDEDOR { get; set; }
        public decimal NIVEL_ENDEUDAMIENTO_CUOTA { get; set; }
        public decimal NIVEL_ENDEUDAMIENTO_AQM { get; set; }
        public string SEXO { get; set; }
        public string PREAPROBADO_EXPERTO { get; set; }
        public string CONSULTA_CIFIN { get; set; }
        public string TOTAL_ACTIVOS { get; set; }
        public string DESCRIPCION_ACTIVOS { get; set; }
        public string TOTAL_PASIVOS { get; set; }
        public string VIVIENDA { get; set; }
        public string VENDEDORES { get; set; }
        public string ALIADO_TECNICO { get; set; }
        public string ALIADO_JURIDICO { get; set; }
        public string RECURSOS_CUENTA_INDIV { get; set; }
        public string RECURSOS_PROPIOS { get; set; }
        public string MODALIDAD_PAGO { get; set; }
        public decimal TOTAL_APORTES_AFILIADO { get; set; }
        public decimal CANON_INICIAL { get; set; }
        public decimal OPCION_COMPRA { get; set; }

    }
}
