/*
Nombre: ENT_ENTIDAD_BANCARIA
Descripcion: Tabla entidad bancaria
Elaboro: Hanson Restrepo
Fecha: Noviembre 18 de 2021
*/

IF OBJECT_ID('ENT_ENTIDAD_BANCARIA', 'U') > 0
BEGIN
	DROP TABLE ENT_ENTIDAD_BANCARIA;
END

CREATE TABLE ENT_ENTIDAD_BANCARIA (
	ENT_ID uniqueidentifier PRIMARY KEY,
	ENT_NOMBRE_RAZON_SOCIAL VARCHAR(100),
	ENT_CODIGO_BANCO INT NOT NULL,
	ENT_ESTADO BIT NOT NULL,
	ENT_CREATEDOPOR uniqueidentifier NOT NULL,
	ENT_FECHACREACION DATETIME NOT NULL,
	ENT_MODIFICADOPOR uniqueidentifier NULL,
	ENT_FECHAMODIFICACION DATETIME NULL
);