/*
Nombre: MAI_MATRICULA_INMOBILIARIA
Descripcion: Tabla matrícula inmobiliaria para solicitud cesantías compra de vivienda
Elaboro: Hanson Restrepo
Fecha: Noviembre 18 de 2021
*/

IF OBJECT_ID('MAI_MATRICULA_INMOBILIARIA', 'U') > 0
BEGIN
	DROP TABLE MAI_MATRICULA_INMOBILIARIA;
END

CREATE TABLE MAI_MATRICULA_INMOBILIARIA (
	MAI_ID uniqueidentifier PRIMARY KEY,
	MAI_NUMERO_MATRICULA VARCHAR(50) NOT NULL,
	MAI_FECHA_REGISTRO DATETIME NOT NULL,
	MAI_DIRECCION VARCHAR(100),
	SOL_ID_FK uniqueidentifier FOREIGN KEY REFERENCES SOL_SOLICITUD (SOL_ID),
	DPC_ID_FK INT FOREIGN KEY REFERENCES DPC_CIUDAD (DPC_ID),
	MAI_PRINCIPAL BIT NOT NULL,
	MAI_ESTADO BIT NOT NULL,
	MAI_CREATEDOPOR uniqueidentifier NOT NULL,
	MAI_FECHACREACION DATETIME NOT NULL,
	MAI_MODIFICADOPOR uniqueidentifier NULL,
	MAI_FECHAMODIFICACION DATETIME NULL
);


