
IF OBJECT_ID('PAM_PARAMETRIZACION_ARHIVOS_MODALIDAD', 'U') > 0
BEGIN
	DROP TABLE PAM_PARAMETRIZACION_ARHIVOS_MODALIDAD
END

CREATE TABLE PAM_PARAMETRIZACION_ARHIVOS_MODALIDAD (
	PAM_ID						UNIQUEIDENTIFIER	 PRIMARY KEY NOT NULL,
	TIM_ID						UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TIM_TIPO_MODALIDAD(TIM_ID) NOT NULL,
	PAM_NOMBRE_ARCHIVO			VARCHAR(100) NOT NULL,
	PAM_DESCRIPCION_ARCHIVO		VARCHAR(1024) NOT NULL,
	PAM_REQUERIDO				BIT NOT NULL,
	PAM_ORDEN					INT NULL,
	PAM_ESTADO					BIT NOT NULL,
	PAM_CREATEDOPOR				UNIQUEIDENTIFIER	NOT NULL,
	PAM_FECHACREACION			DATETIME	NOT NULL,
	PAM_MODIFICADOPOR			UNIQUEIDENTIFIER	NULL,
	PAM_FECHAMODIFICACION		DATETIME NULL
)
