IF OBJECT_ID('PMA_PROPIETARIO_MATRICULA', 'U') > 0
BEGIN
	DROP TABLE PMA_PROPIETARIO_MATRICULA
END

CREATE TABLE PMA_PROPIETARIO_MATRICULA (
	PRP_ID						UNIQUEIDENTIFIER FOREIGN KEY REFERENCES PRP_PROPIETARIO (PRP_ID),
	MAI_ID						UNIQUEIDENTIFIER FOREIGN KEY REFERENCES MAI_MATRICULA_INMOBILIARIA (MAI_ID),
	PMA_ESTADO					BIT NOT NULL,
	PMA_CREATEDOPOR				UNIQUEIDENTIFIER NOT NULL,
	PMA_FECHACREACION			DATETIME NOT NULL,
	PMA_MODIFICADOPOR			UNIQUEIDENTIFIER NULL,
	PMA_FECHAMODIFICACION		DATETIME NULL,
	PRIMARY KEY(PRP_ID,MAI_ID)
)

