IF OBJECT_ID('SOL_SOLICITUD', 'U') > 0
BEGIN
	DROP TABLE SOL_SOLICITUD
END

--sol_solicitud
CREATE TABLE SOL_SOLICITUD (
	SOL_ID						UNIQUEIDENTIFIER	 PRIMARY KEY NOT NULL,
	CTA_ID						INT NULL,
	TPS_SUB_ID					UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TPS_TIPO_SUBMODALIDAD(TPS_SUB_ID) NOT NULL,
	CLI_ID						INT NOT NULL,
	SOL_ESTADO_SOLICITUD		INT FOREIGN KEY REFERENCES CVL_CATALOGO_VALOR(CVL_ID) NOT NULL,
	SOL_FECHA_SOLICITUD			DATETIME NOT NULL,
	SOL_OBSERVACION				VARCHAR(1024) NULL,
	SOL_ESTADO					BIT NOT NULL,
	SOL_CREATEDOPOR				UNIQUEIDENTIFIER	NOT NULL,
	SOL_FECHACREACION			DATETIME	NOT NULL,
	SOL_MODIFICADOPOR			UNIQUEIDENTIFIER	NULL,
	SOL_FECHAMODIFICACION		DATETIME NULL,
	SOL_VALOR_A_RETIRAR			DECIMAL (18,2) NOT NULL
)
