-- =============================================
-- Author:		Oscar Julian Rojas
-- Fecha: 09/08/2021
-- Descripcion:	crear Tarea
-- =============================================
create PROCEDURE ActulizarTarea
	@TRA_ID uniqueidentifier, 
	@PCS_ID uniqueidentifier, 
	@TRA_NOMBRE nvarchar, 
	@TRA_FECHAINICIO datetime, 
	@TRA_FECHAFIN datetime, 
	@TRA_TAREA_CIERRE datetime, 
	@TRA_ACTIVA bit, 
	@RL_ID_RESPONSABLE uniqueidentifier, 
	@TRA_MODIFICADOPOR  uniqueidentifier, 
	@TRA_FECHAMODIFICACION datetime
AS
BEGIN
	
	UPDATE TRA_TAREA
	SET PCS_ID=@PCS_ID, 
	TRA_NOMBRE=@TRA_NOMBRE, 
	TRA_FECHAINICIO=@TRA_FECHAINICIO, 
	TRA_FECHAFIN=@TRA_FECHAFIN, 
	TRA_TAREA_CIERRE=@TRA_TAREA_CIERRE, 
	TRA_ACTIVA=@TRA_ACTIVA, 
	RL_ID_RESPONSABLE=@RL_ID_RESPONSABLE,
	TRA_MODIFICADOPOR=@TRA_MODIFICADOPOR, 
	TRA_FECHAMODIFICACION=@TRA_FECHAMODIFICACION

	WHERE TRA_ID=@TRA_ID

	
	SELECT TRA_ID, PCS_ID, TRA_NOMBRE, TRA_FECHAINICIO, TRA_FECHAFIN, TRA_TAREA_CIERRE, TRA_ACTIVA, RL_ID_RESPONSABLE, TRA_CREATEDOPOR, TRA_FECHACREACION, TRA_MODIFICADOPOR, TRA_FECHAMODIFICACION
	FROM TRA_TAREA WHERE TRA_ID=@TRA_ID

	
END;
