-- =============================================
-- Author:		Oscar Julian Rojas
-- Fecha: 09/08/2021
-- Descripcion:	Actualizar Añadidos
-- =============================================
CREATE PROCEDURE ActualizarAnadido
	@AND_ID uniqueidentifier,
	@TRA_ID uniqueidentifier,
	@AND_NOMBREANADIDO nvarchar,
	@AND_FILE nvarchar,
	@AND_TIPO tinyint,
	@AND_MODIFICADOPOR uniqueidentifier,
	@AND_FECHAMODIFICACION datetime
AS
BEGIN
	
	UPDATE AND_ANADIDOS
	SET TRA_ID=@TRA_ID, 
	AND_NOMBREANADIDO=@AND_NOMBREANADIDO, 
	AND_FILE=@AND_FILE, 
	AND_TIPO=@AND_TIPO, 
	AND_MODIFICADOPOR=@AND_MODIFICADOPOR, 
	AND_FECHAMODIFICACION=@AND_FECHAMODIFICACION
	WHERE AND_ID= @AND_ID
	
	SELECT AND_ID, TRA_ID, AND_NOMBREANADIDO, AND_FILE, AND_TIPO, AND_CREATEDOPOR, AND_FECHACREACION, AND_MODIFICADOPOR, AND_FECHAMODIFICACION
	FROM AND_ANADIDOS WHERE AND_ID=@AND_ID

	
END;
