IF OBJECT_ID('ObtenerTareas', 'P')>0
BEGIN
	DROP PROCEDURE ObtenerTareas
END
GO
CREATE PROCEDURE ObtenerTareas
AS
BEGIN
	SELECT TRA_ID, PCS_ID, TRA_NOMBRE, TRA_FECHAINICIO, TRA_FECHAFIN, TRA_TAREA_CIERRE, TRA_ACTIVA, RL_ID_RESPONSABLE,
    TRA_CREATEDOPOR, TRA_FECHACREACION, TRA_MODIFICADOPOR, TRA_FECHAMODIFICACION, TRA_ID_ENTRADA, TRA_ID_SALIDA
	FROM TRA_TAREA
END