IF OBJECT_ID('ObtenerProcesos', 'P') > 0
BEGIN
	DROP PROCEDURE ObtenerProcesos
END
GO
CREATE PROCEDURE ObtenerProcesos
AS
BEGIN 
	SELECT PCS_ID, PCS_NOMBRE, PCS_DESCRIPCION, PSC_VERSION, PCS_ESTADO, PSC_CREATEDOPOR, PSC_FECHACREACION,
	PSC_MODIFICADOPOR FROM PSC_PROCESO WHERE PCS_ESTADO = 1
END