/*
Nombre: TIPO_DOCUMENTO
Descripcion: Tabla TIPO_DOCUMENTO
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/

IF OBJECT_ID('GA2.dbo.TDC_TIPO_DOCUMENTO') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.TDC_TIPO_DOCUMENTO;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.TDC_TIPO_DOCUMENTO (
	TDC_ID int IDENTITY(1,1) NOT NULL,
	TDC_DESCRIPCION varchar(70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	TDC_ESTADO int NOT NULL,
	TDC_CREADO_POR uniqueidentifier NOT NULL,
	TDC_FECHA_CREACION datetime NOT NULL,
	TDC_MODIFICADO_POR uniqueidentifier NULL,
	TDC_FECHA_MODIFICACION datetime NULL,
	CONSTRAINT PK_TDC_TIPO_DOCUMENTO PRIMARY KEY (TDC_ID)
);
END