USE [GA2]
GO

/****** Object:  Table [dbo].[SOB_SOLICITUD_INF_BASICA]    Script Date: 6/07/2021 9:11:23 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SOB_SOLICITUD_INF_BASICA](
	[SOB_ID] [uniqueidentifier] NOT NULL,
	[SOC_ID] [uniqueidentifier] NOT NULL,
	[TID_ID] [int] NOT NULL,
	[SOB_NUMERO_DOCUMENTO] [varchar](20) NOT NULL,
	[SOB_FECHA_EXPEDICION] [date] NOT NULL,
	[DPD_ID_EXP] [int] NOT NULL,
	[DPC_ID_EXP] [int] NOT NULL,
	[SOB_PRIMER_APELLIDO] [varchar](20) NOT NULL,
	[SOB_SEGUNDO_APELLIDO] [varchar](20) NULL,
	[SOB_PRIMER_NOMBRE] [varchar](20) NOT NULL,
	[SOB_SEGUNDO_NOMBRE] [varchar](20) NULL,
	[SOB_FECHA_NACIMIENTO] [date] NOT NULL,
	[DPD_ID_NACIMIENTO] [int] NOT NULL,
	[DPC_ID_NACIMIENTO] [int] NOT NULL,
	[SOB_SEXO] [varchar](5) NULL,
	[SOB_ESTADO_CIVIL] [varchar](5) NULL,
	[SOB_NIVEL_EDUCACION] [varchar](5) NULL,
	[FRZ_ID] [int] NOT NULL,
	[CTG_ID] [int] NOT NULL,
	[GRD_ID] [int] NOT NULL,
	[DPD_ID_RESIDENCIA] [int] NOT NULL,
	[DPC_ID_RESIDENCIA] [int] NOT NULL,
	[SOB_DIRECCION_RESIDENCIA] [varchar](255) NOT NULL,
	[SOB_CORREO_PERSONAL] [varchar](100) NOT NULL,
	[SOB_TELEFONO_RESIDENCIA] [varchar](20) NOT NULL,
	[SOB_CELULAR] [varchar](20) NOT NULL,
	[DPD_ID_OFICINA] [int] NULL,
	[DPC_ID_OFICINA] [int] NULL,
	[SOB_DIRECCION_OFICINA] [varchar](255) NULL,
	[SOB_CORREO_INSTITUCIONAL] [varchar](100) NOT NULL,
	[SOB_TELEFONO_OFICINA] [varchar](20) NOT NULL,
	[ACC_ID] [int] NOT NULL,
	[PRF_ID] [int] NOT NULL,
	[SOB_TIENE_TRANSACCION_ME] [varchar](2) NOT NULL,
	[SOB_TIPO_TRANSACCION_ME] [varchar](5) NULL,
	[SOB_TIPO_PRODUCTO_ME] [varchar](5) NULL,
	[SOB_BANCO_TRANSACCION_ME] [varchar](50) NULL,
	[SOB_NUMERO_PRODUCTO_ME] [varchar](50) NULL,
	[SOB_SALDO_PROMEDIO_CUENTAS_ME] [float] NULL,
	[SOB_MONEDA_TRANSACCION_ME] [varchar](5) NULL,
	[DPP_ID_ME] [int] NOT NULL,
	[DPD_ID_ME] [int] NOT NULL,
	[SOB_CREADO_POR] [uniqueidentifier] NOT NULL,
	[SOB_FECHA_CREACION] [datetime] NOT NULL,
	[SOB_ACTUALIZADO_POR] [uniqueidentifier] NOT NULL,
	[SOB_FECHA_ACTUALIZA] [datetime] NOT NULL,
 CONSTRAINT [PK_SOB_SOLICITUD_INF_BASICA] PRIMARY KEY CLUSTERED 
(
	[SOB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA]  WITH CHECK ADD  CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPC_CIUDAD] FOREIGN KEY([DPC_ID_EXP])
REFERENCES [dbo].[DPC_CIUDAD] ([DPC_ID])
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA] CHECK CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPC_CIUDAD]
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA]  WITH CHECK ADD  CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPC_CIUDAD1] FOREIGN KEY([DPC_ID_RESIDENCIA])
REFERENCES [dbo].[DPC_CIUDAD] ([DPC_ID])
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA] CHECK CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPC_CIUDAD1]
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA]  WITH CHECK ADD  CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPC_CIUDAD2] FOREIGN KEY([DPC_ID_OFICINA])
REFERENCES [dbo].[DPC_CIUDAD] ([DPC_ID])
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA] CHECK CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPC_CIUDAD2]
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA]  WITH CHECK ADD  CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPD_DEPARTAMENTO] FOREIGN KEY([DPD_ID_EXP])
REFERENCES [dbo].[DPD_DEPARTAMENTO2] ([DPD_ID])
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA] CHECK CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPD_DEPARTAMENTO]
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA]  WITH CHECK ADD  CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPD_DEPARTAMENTO1] FOREIGN KEY([DPD_ID_NACIMIENTO])
REFERENCES [dbo].[DPD_DEPARTAMENTO2] ([DPD_ID])
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA] CHECK CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPD_DEPARTAMENTO1]
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA]  WITH CHECK ADD  CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPD_DEPARTAMENTO2] FOREIGN KEY([DPD_ID_OFICINA])
REFERENCES [dbo].[DPD_DEPARTAMENTO2] ([DPD_ID])
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA] CHECK CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPD_DEPARTAMENTO2]
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA]  WITH CHECK ADD  CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPD_DEPARTAMENTO3] FOREIGN KEY([DPD_ID_ME])
REFERENCES [dbo].[DPD_DEPARTAMENTO2] ([DPD_ID])
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA] CHECK CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPD_DEPARTAMENTO3]
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA]  WITH CHECK ADD  CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPP_PAIS] FOREIGN KEY([DPP_ID_ME])
REFERENCES [dbo].[DPP_PAIS2] ([DPP_ID])
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA] CHECK CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_DPP_PAIS]
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA]  WITH CHECK ADD  CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_SOC_SOLICITUD_CREDITO] FOREIGN KEY([SOC_ID])
REFERENCES [dbo].[SOC_SOLICITUD_CREDITO] ([SOC_ID])
GO

ALTER TABLE [dbo].[SOB_SOLICITUD_INF_BASICA] CHECK CONSTRAINT [FK_SOB_SOLICITUD_INF_BASICA_SOC_SOLICITUD_CREDITO]
GO


