/*
Nombre: ASEGURADORAS
Descripcion: Tablas ASEGURADORAS
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/
IF OBJECT_ID('GA2.dbo.ASE_ASEGURADORAS') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.ASE_ASEGURADORAS;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.ASE_ASEGURADORAS (
	ASE_ID int IDENTITY(1,1) NOT NULL,
	ASE_RAZON_SOCIAL varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ASE_SITIO_WEB varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ASE_ESTADO int NOT NULL,
	ASE_CREADO_POR uniqueidentifier NOT NULL,
	ASE_FECHA_CREACION datetime NOT NULL,
	ASE_ACTUALIZADO_POR uniqueidentifier NOT NULL,
	ASE_FECHA_ACTUALIZA datetime NOT NULL,
	CONSTRAINT PK_ASE_ASEGURADORAS PRIMARY KEY (ASE_ID)
);
END