/*
Nombre: ACTIVIDAD_FLUJO
Descripcion: Tabla ACTIVIDAD_FLUJO
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/

IF OBJECT_ID('GA2.dbo.AFL_ACTIVIDAD_FLUJO') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.AFL_ACTIVIDAD_FLUJO;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.AFL_ACTIVIDAD_FLUJO (
	AFL_ID int IDENTITY(1,1) NOT NULL,
	FLU_ID int NOT NULL,
	TAC_ID int NOT NULL,
	AFL_ORDEN int NOT NULL,
	AFL_TIEMPO int NOT NULL,
	AFL_ACTIVIDAD_AUTOMATICA char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AFL_ACTIVIDAD_PRINCIPAL char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AFL_PUEDE_DELEGAR char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AFL_CARGA_ARCHIVOS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AFL_VISUALIZA_ARCHIVOS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AFL_CAPTURA_DATOS_TEC char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AFL_CAPTURA_DATOS_JUR char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'N' NOT NULL,
	AFL_CAPTURA_DATOS_FIN char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'N' NOT NULL,
	AFL_VISUALIZA_DATOS_BAS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'N' NOT NULL,
	AFL_VIISUALIZA_DATOS_GAR char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'N' NOT NULL,
	AFL_VISUALIZA_DATOS_FIN char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'N' NOT NULL,
	AFL_GENERA_PDF_RESUMEN char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'N' NOT NULL,
	AFL_CONSULTA_BURO char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'N' NOT NULL,
	AFL_ENVIO_NOTIFICACION char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AFL_ENVIO_NOTIFICACION_VENC char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AFL_ENVIA_NOTIFICACION_CLIENTE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'N' NOT NULL,
	AFL_ESTADO int NOT NULL,
	AFL_CREADO_POR uniqueidentifier NOT NULL,
	AFL_FECHA_CREACION datetime NOT NULL,
	AFL_MODIFICADO_POR uniqueidentifier NULL,
	AFL_FECHA_MODIFICACION datetime NULL,
	CONSTRAINT PK_AFL_ACTIVIDAD_FLUJO PRIMARY KEY (AFL_ID)
);
END