/*
Nombre: ACTIVIDAD_TRAMITE_SOLIC
Descripcion: Tabla ACTIVIDAD_TRAMITE_SOLIC
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/

IF OBJECT_ID('GA2.dbo.ACT_ACTIVIDAD_TRAMITE_SOLIC') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.ACT_ACTIVIDAD_TRAMITE_SOLIC;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.ACT_ACTIVIDAD_TRAMITE_SOLIC (
	ACT_ID uniqueidentifier NOT NULL,
	TRS_ID uniqueidentifier NOT NULL,
	AFL_ID int NOT NULL,
	ID_USERS uniqueidentifier NOT NULL,
	ACT_FECHA_INICIO date NOT NULL,
	ACT_FECHA_FINALIZA date NULL,
	ACT_OBSERVACION varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACT_ESTADO int NOT NULL,
	ACT_CREADO_POR uniqueidentifier NOT NULL,
	ACT_FECHA_CREACION datetime NOT NULL,
	ACT_APROBADO_POR uniqueidentifier NULL,
	ACT_FECHA_APROBACION datetime NULL,
	ACT_MODIFICADO_POR uniqueidentifier NULL,
	ACT_FECHA_MODIFICACION datetime NULL,
	CONSTRAINT PK_ACT_ACTIVIDAD_TRAMITE_SOLIC PRIMARY KEY (ACT_ID),
	CONSTRAINT FK_ACT_ACTIVIDAD_TRAMITE_SOLIC_ACT_ACTIVIDAD_TRAMITE_SOLIC FOREIGN KEY (ACT_ID) REFERENCES GA2.dbo.ACT_ACTIVIDAD_TRAMITE_SOLIC(ACT_ID),
	CONSTRAINT FK_ACT_ACTIVIDAD_TRAMITE_SOLIC_AFL_ACTIVIDAD_FLUJO FOREIGN KEY (AFL_ID) REFERENCES GA2.dbo.AFL_ACTIVIDAD_FLUJO(AFL_ID)
);
END