/*
Nombre: DOCUMENTO_ACTIVIDAD
Descripcion: Tabla DOCUMENTO_ACTIVIDAD
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/

IF OBJECT_ID('GA2.dbo.DCA_DOCUMENTO_ACTIVIDAD') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.DCA_DOCUMENTO_ACTIVIDAD;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.DCA_DOCUMENTO_ACTIVIDAD (
	DCA_ID int IDENTITY(1,1) NOT NULL,
	AFL_ID int NOT NULL,
	TDC_ID int NOT NULL,
	DCA_ORDEN int NOT NULL,
	DCA_OBLIGATORIO char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DCA_CARGA char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'N' NOT NULL,
	DCA_VISUALIZA char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'N' NOT NULL,
	DCA_VISUALIZA_CLIENTE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'N' NOT NULL,
	DCA_ESTADO int NOT NULL,
	DCA_CREADO_POR uniqueidentifier NULL,
	DCA_FECHA_CREACION datetime NOT NULL,
	DCA_MODIFICADO_POR uniqueidentifier NULL,
	DCA_FECHA_MODIFICACION datetime NULL,
	CONSTRAINT PK_DCA_DOCUMENTO_ACTIVIDAD PRIMARY KEY (DCA_ID)
);
END
