USE [GA2]
GO

/****** Object:  Table [dbo].[SID_SOLICITUD_INF_DESEMBOLSO]    Script Date: 6/07/2021 7:19:32 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SID_SOLICITUD_INF_DESEMBOLSO](
	[SID_ID] [uniqueidentifier] NOT NULL,
	[SOC_ID] [uniqueidentifier] NOT NULL,
	[FRC_ID] [int] NOT NULL,
	[SID_VALOR_DESEMBOLSO] [decimal](22, 0) NOT NULL,
	[SID_FECHA_DESEMBOLSO] [date] NOT NULL,
	[SID_APLICADO] [char](1) NOT NULL,
	[SID_APLICADO_POR] [uniqueidentifier] NULL,
	[SID_FECHA_APLICACION] [datetime] NULL,
	[SID_ANULADO] [char](1) NOT NULL,
	[CDD_ID] [int] NULL,
	[SID_ANULADO_POR] [uniqueidentifier] NULL,
	[SID_FECHA_ANULACION] [datetime] NULL,
	[SID_OBSERVACION_ANULACION] [varchar](1000) NULL,
	[SID_CREADO_POR] [uniqueidentifier] NOT NULL,
	[SID_FECHA_CREACION] [datetime] NOT NULL,
	[SID_ACTUALIZADO_POR] [uniqueidentifier] NULL,
	[SID_FECHA_ACTUALIZA] [datetime] NULL,
 CONSTRAINT [PK_SID_SOLICITUD_INF_DESEMBOLSO] PRIMARY KEY CLUSTERED 
(
	[SID_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SID_SOLICITUD_INF_DESEMBOLSO]  WITH CHECK ADD  CONSTRAINT [FK_SID_SOLICITUD_INF_DESEM_SOC_SOLICITUD_CREDITO] FOREIGN KEY([SOC_ID])
REFERENCES [dbo].[SOC_SOLICITUD_CREDITO] ([SOC_ID])
GO

ALTER TABLE [dbo].[SID_SOLICITUD_INF_DESEMBOLSO] CHECK CONSTRAINT [FK_SID_SOLICITUD_INF_DESEM_SOC_SOLICITUD_CREDITO]
GO


