/*
Nombre: SIT_SOLICITUD_INF_TECNICA
Descripcion: Tabla solicitud informacion tecnica
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/

IF OBJECT_ID('GA2.dbo.SIT_SOLICITUD_INF_TECNICA') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.SIT_SOLICITUD_INF_TECNICA;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.SIT_SOLICITUD_INF_TECNICA (
	SIT_ID uniqueidentifier NOT NULL,
	SOC_ID uniqueidentifier NOT NULL,
	SIT_VALOR_AVALUO_COMERCIAL decimal(22,0) NOT NULL,
	SIT_VALOR_VENTA_INMUEBLE decimal(22,0) NOT NULL,
	SIT_CONSIDERACIONES_FINALES varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIT_DECLARA_CUMPLIMIENTO varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIT_CONDICIONES_SALVEADES varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIT_CONCEPTO_EST_TECNICO varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIT_CREADO_POR uniqueidentifier NOT NULL,
	SIT_FECHA_CREACION datetime NOT NULL,
	SIT_ACTUALIZADO_POR uniqueidentifier NOT NULL,
	SIT_FECHA_ACTUALIZA datetime NOT NULL,
	CONSTRAINT PK_SOLICITUD_INF_TECNICA PRIMARY KEY (SIT_ID),
	CONSTRAINT FK_SIT_SOLICITUD_INF_TECNICA_SOC_SOLICITUD_CREDITO FOREIGN KEY (SOC_ID) REFERENCES GA2.dbo.SOC_SOLICITUD_CREDITO(SOC_ID)
);
END