USE [GA2]
GO

/****** Object:  Table [dbo].[COI_COMITE_INTEGRANTES]    Script Date: 6/07/2021 9:00:00 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COI_COMITE_INTEGRANTES](
	[COI_ID] [uniqueidentifier] NOT NULL,
	[COC_ID] [bigint] NOT NULL,
	[ICO_ID] [int] NOT NULL,
	[COI_ORDEN] [int] NOT NULL,
	[COI_CREADO_POR] [uniqueidentifier] NOT NULL,
	[COI_FECHA_CREACION] [datetime] NOT NULL,
 CONSTRAINT [PK_COI_COMITE_INTEGRANTES] PRIMARY KEY CLUSTERED 
(
	[COI_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


