/*
Nombre: TIPO_ACTIVIDAD
Descripcion: Tabla TIPO_ACTIVIDAD
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/
IF OBJECT_ID('GA2.dbo.TAC_TIPO_ACTIVIDAD') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.TAC_TIPO_ACTIVIDAD;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.TAC_TIPO_ACTIVIDAD (
	TAC_ID int IDENTITY(1,1) NOT NULL,
	TAC_DESCRIPCION varchar(70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	TAC_ESTADO int NOT NULL,
	TAC_CREADO_POR uniqueidentifier NOT NULL,
	TAC_FECHA_CREACION datetime NOT NULL,
	TAC_MODIFICADO_POR uniqueidentifier NULL,
	TAC_FECHA_MODIFICACION datetime NULL,
	CONSTRAINT PK_TAC_TIPO_ACTIVIDAD PRIMARY KEY (TAC_ID)
);
END