/*
Nombre: SIJ_SOLICITUD_INF_JURIDICA
Descripcion: Tabla solicitud informacion juridica
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/
IF OBJECT_ID('GA2.dbo.SIJ_SOLICITUD_INF_JURIDICA') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.SIJ_SOLICITUD_INF_JURIDICA;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.SIJ_SOLICITUD_INF_JURIDICA (
	SIJ_ID uniqueidentifier NOT NULL,
	SOC_ID uniqueidentifier NOT NULL,
	SIJ_LINDEROS varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIJ_TIPO_PARQUEADERO varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIJ_EDAD_JURIDICA int NOT NULL,
	SIJ_FECHA_PRIMER_ACTO date NOT NULL,
	SIJ_TRADICION_INMUEBLE varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIJ_ANALISIS_ULT_20_AÑOS varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIJ_ANALISIS_SIT_JURIDICA varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIJ_ANALISIS_REG_PROP_HOR varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIJ_ANALISIS_PAZ_Y_SALVO varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIJ_ANALISIS_VENDEDOR varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIJ_VIABILIDAD_JUR_NEGOCIO varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIJ_RECOMENDACIONES varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIJ_CONCEPTO_JURIDICO_FIN varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIJ_CONCEPTO_EST_JURIDICO varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SIJ_CREADO_POR uniqueidentifier NOT NULL,
	SIJ_FECHA_CREACION datetime NOT NULL,
	SIJ_ACTUALIZADO_POR uniqueidentifier NOT NULL,
	SIJ_FECHA_ACTUALIZA datetime NOT NULL,
	CONSTRAINT PK_SIJ_SOLICITUD_INF_JURIDICA PRIMARY KEY (SIJ_ID),
	CONSTRAINT FK_SIJ_SOLICITUD_INF_JURIDICA_SOC_SOLICITUD_CREDITO FOREIGN KEY (SOC_ID) REFERENCES GA2.dbo.SOC_SOLICITUD_CREDITO(SOC_ID)
);
END