/*
Nombre: SJI_SOLICITUD_INF_JUR_INM
Descripcion: Tablas solicitud informacion juridica
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/
IF OBJECT_ID('GA2.dbo.SJI_SOLICITUD_INF_JUR_INM') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.SJI_SOLICITUD_INF_JUR_INM;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.SJI_SOLICITUD_INF_JUR_INM (
	SJI_ID uniqueidentifier NOT NULL,
	SIJ_ID uniqueidentifier NOT NULL,
	SOC_ID uniqueidentifier NOT NULL,
	SJI_NUMERO_MATRICULA varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SJI_CEDULA_CATASTRAL varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SJI_AREA_PRIVADA decimal(9,3) NOT NULL,
	SJI_VALOR_AVALUO_COMERCIAL decimal(22,0) NOT NULL,
	SJI_VALOR_AVALUO_CATASTRAL decimal(22,0) NOT NULL,
	SJI_CREADO_POR uniqueidentifier NOT NULL,
	SJI_FECHA_CREACION datetime NOT NULL,
	SJI_ACTUALIZADO_POR uniqueidentifier NOT NULL,
	SJI_FECHA_ACTUALIZA datetime NOT NULL,
	CONSTRAINT PK_SJI_SOLICITUD_INF_JUR_INM PRIMARY KEY (SJI_ID),
	CONSTRAINT FK_SJI_SOLICITUD_INF_JUR_INM_SOC_SOLICITUD_CREDITO FOREIGN KEY (SOC_ID) REFERENCES GA2.dbo.SOC_SOLICITUD_CREDITO(SOC_ID)
);
END