/*
Nombre: SOF_SOLICITUD_INF_FINANCIERA
Descripcion: Tabla solicitud informacion financiera
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/
IF OBJECT_ID('GA2.dbo.SOF_SOLICITUD_INF_FINANCIERA') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.SOF_SOLICITUD_INF_FINANCIERA;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.SOF_SOLICITUD_INF_FINANCIERA (
	SOF_ID uniqueidentifier NOT NULL,
	SOC_ID uniqueidentifier NOT NULL,
	SOF_CONCEPTO_SALARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOF_VALOR_CONCEPTO_SALARIO decimal(25,6) NOT NULL,
	SOF_CONCEPTO_1 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOF_VALOR_CONCEPTO_1 decimal(25,6) NOT NULL,
	SOF_CONCEPTO_2 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOF_VALOR_CONCEPTO_2 decimal(25,6) NOT NULL,
	SOF_CONCEPTO_3 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOF_VALOR_CONCEPTO_3 decimal(25,6) NOT NULL,
	SOF_CONCEPTO_4 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOF_VALOR_CONCEPTO_4 decimal(25,6) NOT NULL,
	SOF_CONCEPTO_5 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOF_VALOR_CONCEPTO_5 decimal(25,6) NOT NULL,
	SOF_CONCEPTO_6 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOF_VALOR_CONCEPTO_6 decimal(25,6) NOT NULL,
	SOF_VALOR_TOTAL_INGRESOS decimal(25,6) NOT NULL,
	SOF_VALOR_TOTAL_EGRESOS decimal(25,6) NOT NULL,
	SOF_DIRECCION_VIVIENDA varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOF_MATRICULA_VIVIENDA varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOF_VALOR_COMERCIAL_VIVIENDA float NULL,
	SOF_MARCA_VEHICULO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOF_PLACA_VEHICULO varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOF_VALOR_COMERCIAL_VEHICULO float NULL,
	SOF_CREADO_POR uniqueidentifier NOT NULL,
	SOF_FECHA_CREACION datetime NOT NULL,
	SOF_ACTUALIZADO_POR uniqueidentifier NOT NULL,
	SOF_FECHA_ACTUALIZA datetime NOT NULL,
	CONSTRAINT PK_SOF_SOLICITUD_INF_FINANCIERA PRIMARY KEY (SOF_ID),
	CONSTRAINT FK_SOF_SOLICITUD_INF_FINANCIERA_SOC_SOLICITUD_CREDITO FOREIGN KEY (SOC_ID) REFERENCES GA2.dbo.SOC_SOLICITUD_CREDITO(SOC_ID)
);
END