/*
Nombre: SOLICITUD_INF_BASICA
Descripcion: Tabla SOLICITUD_INF_BASICA
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/

-- Drop table

-- DROP TABLE GA2.dbo.SOB_SOLICITUD_INF_BASICA;
IF OBJECT_ID('GA2.dbo.SOB_SOLICITUD_INF_BASICA') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.SOB_SOLICITUD_INF_BASICA;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.SOB_SOLICITUD_INF_BASICA (
	SOB_ID uniqueidentifier NOT NULL,
	SOC_ID uniqueidentifier NOT NULL,
	TID_ID int NOT NULL,
	SOB_NUMERO_DOCUMENTO varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SOB_FECHA_EXPEDICION date NOT NULL,
	DPD_ID_EXP int NOT NULL,
	DPC_ID_EXP int NOT NULL,
	SOB_PRIMER_APELLIDO varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SOB_SEGUNDO_APELLIDO varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOB_PRIMER_NOMBRE varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SOB_SEGUNDO_NOMBRE varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOB_FECHA_NACIMIENTO date NOT NULL,
	DPD_ID_NACIMIENTO int NOT NULL,
	DPC_ID_NACIMIENTO int NOT NULL,
	SOB_SEXO varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOB_ESTADO_CIVIL varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOB_NIVEL_EDUCACION varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FRZ_ID int NOT NULL,
	CTG_ID int NOT NULL,
	GRD_ID int NOT NULL,
	DPD_ID_RESIDENCIA int NOT NULL,
	DPC_ID_RESIDENCIA int NOT NULL,
	SOB_DIRECCION_RESIDENCIA varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SOB_CORREO_PERSONAL varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SOB_TELEFONO_RESIDENCIA varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SOB_CELULAR varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DPD_ID_OFICINA int NULL,
	DPC_ID_OFICINA int NULL,
	SOB_DIRECCION_OFICINA varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOB_CORREO_INSTITUCIONAL varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SOB_TELEFONO_OFICINA varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ACC_ID int NOT NULL,
	PRF_ID int NOT NULL,
	SOB_TIENE_TRANSACCION_ME varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SOB_TIPO_TRANSACCION_ME varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOB_TIPO_PRODUCTO_ME varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOB_BANCO_TRANSACCION_ME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOB_NUMERO_PRODUCTO_ME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOB_SALDO_PROMEDIO_CUENTAS_ME float NULL,
	SOB_MONEDA_TRANSACCION_ME varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DPP_ID_ME int NOT NULL,
	DPD_ID_ME int NOT NULL,
	SOB_CREADO_POR uniqueidentifier NOT NULL,
	SOB_FECHA_CREACION datetime NOT NULL,
	SOB_ACTUALIZADO_POR uniqueidentifier NOT NULL,
	SOB_FECHA_ACTUALIZA datetime NOT NULL,
	CONSTRAINT PK_SOB_SOLICITUD_INF_BASICA PRIMARY KEY (SOB_ID),
	CONSTRAINT FK_SOB_SOLICITUD_INF_BASICA_DPC_CIUDAD FOREIGN KEY (DPC_ID_EXP) REFERENCES GA2.dbo.DPC_CIUDAD(DPC_ID),
	CONSTRAINT FK_SOB_SOLICITUD_INF_BASICA_DPC_CIUDAD1 FOREIGN KEY (DPC_ID_RESIDENCIA) REFERENCES GA2.dbo.DPC_CIUDAD(DPC_ID),
	CONSTRAINT FK_SOB_SOLICITUD_INF_BASICA_DPC_CIUDAD2 FOREIGN KEY (DPC_ID_OFICINA) REFERENCES GA2.dbo.DPC_CIUDAD(DPC_ID),
	CONSTRAINT FK_SOB_SOLICITUD_INF_BASICA_DPD_DEPARTAMENTO FOREIGN KEY (DPD_ID_EXP) REFERENCES GA2.dbo.DPD_DEPARTAMENTO(DPD_ID),
	CONSTRAINT FK_SOB_SOLICITUD_INF_BASICA_DPD_DEPARTAMENTO1 FOREIGN KEY (DPD_ID_NACIMIENTO) REFERENCES GA2.dbo.DPD_DEPARTAMENTO(DPD_ID),
	CONSTRAINT FK_SOB_SOLICITUD_INF_BASICA_DPD_DEPARTAMENTO2 FOREIGN KEY (DPD_ID_OFICINA) REFERENCES GA2.dbo.DPD_DEPARTAMENTO(DPD_ID),
	CONSTRAINT FK_SOB_SOLICITUD_INF_BASICA_DPD_DEPARTAMENTO3 FOREIGN KEY (DPD_ID_ME) REFERENCES GA2.dbo.DPD_DEPARTAMENTO(DPD_ID),
	CONSTRAINT FK_SOB_SOLICITUD_INF_BASICA_DPP_PAIS FOREIGN KEY (DPP_ID_ME) REFERENCES GA2.dbo.DPP_PAIS(DPP_ID),
	CONSTRAINT FK_SOB_SOLICITUD_INF_BASICA_SOC_SOLICITUD_CREDITO FOREIGN KEY (SOC_ID) REFERENCES GA2.dbo.SOC_SOLICITUD_CREDITO(SOC_ID),
	CONSTRAINT FK_SOB_SOLICITUD_INF_BASICA_TID_TIPO_IDENTIFICACION FOREIGN KEY (TID_ID) REFERENCES GA2.dbo.TID_TIPO_IDENTIFICACION(TID_ID)
);
END