/*
Nombre: GRD_GRADO
Descripcion: Tabla grado
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/
IF OBJECT_ID('GA2.dbo.GRD_GRADO') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.GRD_GRADO;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.GRD_GRADO (
	GRD_ID int NOT NULL,
	GRD_DESCRIPCION varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CTG_ID int NOT NULL,
	GRD_ESPECIAL int NOT NULL,
	GRD_CODIGO int NOT NULL,
	GRD_SIGLA varchar(7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	FRZ_ID int NOT NULL,
	GRD_CIVIL int NOT NULL,
	GRD_ACTIVO int NOT NULL,
	GRD_FACTOR_SBS int NULL,
	CONSTRAINT PK_GRD_GRADO PRIMARY KEY (GRD_ID)
);
END