USE [GA2]
GO

/****** Object:  Table [dbo].[COS_COMITE_SOLICITUD_CREDITO]    Script Date: 6/07/2021 9:02:27 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COS_COMITE_SOLICITUD_CREDITO](
	[COS_ID] [uniqueidentifier] NOT NULL,
	[SOC_ID] [uniqueidentifier] NOT NULL,
	[COC_ID] [bigint] NOT NULL,
	[COS_RESULTADO] [varchar](1000) NOT NULL,
	[COS_APROBADA] [char](1) NOT NULL,
	[COS_RECHAZADA] [char](1) NOT NULL,
	[COS_VALOR_CREDITO] [float] NULL,
	[COS_PLAZO_CREDITO] [int] NULL,
	[COS_TEA_CREDITO] [decimal](6, 3) NULL,
	[COS_CREADO_POR] [uniqueidentifier] NOT NULL,
	[COS_FECHA_CREACION] [datetime] NOT NULL,
	[COS_ACTUALIZADO_POR] [uniqueidentifier] NULL,
	[COS_FECHA_ACTUALIZACION] [datetime] NULL,
 CONSTRAINT [PK_COS_COMITE_SOLICITUD_CREDITO] PRIMARY KEY CLUSTERED 
(
	[COS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


