/*
Nombre: CTG_CATEGORIA
Descripcion: Tabla categoria
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/
IF OBJECT_ID('GA2.dbo.CTG_CATEGORIA') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.CTG_CATEGORIA;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.CTG_CATEGORIA (
	CTG_ID int NOT NULL,
	CTG_DESCRIPCION varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_CTG_CATEGORIA PRIMARY KEY (CTG_ID)
);
END