/*
Nombre: TRAMITE_SOLICITUD
Descripcion: Tabla TRAMITE_SOLICITUD
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/

IF OBJECT_ID('GA2.dbo.TRS_TRAMITE_SOLICITUD') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.TRS_TRAMITE_SOLICITUD;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.TRS_TRAMITE_SOLICITUD (
	TRS_ID uniqueidentifier NOT NULL,
	FLU_ID int NOT NULL,
	SOC_ID uniqueidentifier NOT NULL,
	TRS_OBSERVACION varchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	TRS_ULTIMA_ACTIVIDAD int NOT NULL,
	TRS_FECHA_INICIO datetime NOT NULL,
	TRS_FECHA_FINALIZACION datetime NULL,
	ID_USUARIO_PERITO uniqueidentifier NULL,
	TRS_CREADO_POR uniqueidentifier NOT NULL,
	TRS_FECHA_CREACION datetime NOT NULL,
	TRS_MODIFICADO_POR uniqueidentifier NULL,
	TRS_FECHA_MODIFICACION datetime NULL,
	CONSTRAINT PK_TRS_TRAMITE_SOLICITUD PRIMARY KEY (TRS_ID),
	CONSTRAINT FK_TRS_TRAMITE_SOLICITUD_SOC_SOLICITUD_CREDITO FOREIGN KEY (SOC_ID) REFERENCES GA2.dbo.SOC_SOLICITUD_CREDITO(SOC_ID)
);
END