USE [GA2]
GO

/****** Object:  Table [dbo].[COT_COMITE_TEMAS_TRATADOS]    Script Date: 6/07/2021 9:03:23 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COT_COMITE_TEMAS_TRATADOS](
	[COT_ID] [uniqueidentifier] NOT NULL,
	[COC_ID] [bigint] NOT NULL,
	[TCO_ID] [int] NOT NULL,
	[COT_ORDEN] [int] NOT NULL,
	[COT_OBSERVACION] [varchar](1000) NOT NULL,
	[COT_CREADO_POR] [uniqueidentifier] NOT NULL,
	[COT_FECHA_CREACION] [datetime] NOT NULL,
 CONSTRAINT [PK_COT_COMITE_TEMAS_TRATADOS] PRIMARY KEY CLUSTERED 
(
	[COT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


