/*
Nombre: DOCUMENTO_SOLIC_CREDITO
Descripcion: Tabla DOCUMENTO_SOLIC_CREDITO
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/

IF OBJECT_ID('GA2.dbo.DCS_DOCUMENTO_SOLIC_CREDITO') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.DCS_DOCUMENTO_SOLIC_CREDITO;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.DCS_DOCUMENTO_SOLIC_CREDITO (
	DCS_ID uniqueidentifier NOT NULL,
	SOC_ID uniqueidentifier NOT NULL,
	TDC_ID int NOT NULL,
	DCS_CODIGO_BARRAS varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DCS_FECHA_DOCUMENTO date NOT NULL,
	DCS_NUMERO_FOLIOS int NOT NULL,
	DCS_TAMAÑO int NOT NULL,
	DCS_RUTA_IMAGEN varchar(400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DCS_ESTADO int NOT NULL,
	DCS_CREADO_POR uniqueidentifier NULL,
	DCS_FECHA_CREACION datetime NOT NULL,
	DCS_MODIFICADO_POR uniqueidentifier NULL,
	DCS_FECHA_MODIFICACION datetime NULL,
	CONSTRAINT PK_DCS_DOCUMENTO_SOLIC_CREDITO PRIMARY KEY (DCS_ID),
	CONSTRAINT FK_DCS_DOCUMENTO_SOLIC_CREDITO_SOC_SOLICITUD_CREDITO FOREIGN KEY (SOC_ID) REFERENCES GA2.dbo.SOC_SOLICITUD_CREDITO(SOC_ID),
	CONSTRAINT FK_DCS_DOCUMENTO_SOLIC_CREDITO_TDC_TIPO_DOCUMENTO FOREIGN KEY (TDC_ID) REFERENCES GA2.dbo.TDC_TIPO_DOCUMENTO(TDC_ID)
);
END
