/*
Nombre: SOLICITUD_CREDITO
Descripcion: Tabla SOLICITUD_CREDITO
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/
IF OBJECT_ID('GA2.dbo.SOC_SOLICITUD_CREDITO') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.SOC_SOLICITUD_CREDITO;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.SOC_SOLICITUD_CREDITO (
	SOC_ID uniqueidentifier NOT NULL,
	SOC_FECHA_SOLICITUD date NOT NULL,
	SOC_NUMERO_SOLICITUD bigint NOT NULL,
	TCR_ID int NOT NULL,
	DPD_ID int NOT NULL,
	DPC_ID int NOT NULL,
	SLS_ID uniqueidentifier NOT NULL,
	TID_ID int NOT NULL,
	CLI_IDENTIFICACION varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SOC_DECLARACION_ORIGEN_FONDOS varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SOC_AUTORIZA_USO_DATOS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SOC_AUTORIZA_CONSULTA_CENTRALES char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SOC_DECLARACION_ASEGURABILIDAD char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SOC_CONVENIO_ASEGURADORA char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ASE_ID int NOT NULL,
	SOC_ESTADO char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SOC_CREADO_POR uniqueidentifier NOT NULL,
	SOC_FECHA_CREACION datetime NOT NULL,
	SOC_ACTUALIZADO_POR uniqueidentifier NULL,
	SOC_FECHA_ACTUALIZA datetime NULL,
	CONSTRAINT PK_SOC_SOLICITUD_CREDITO PRIMARY KEY (SOC_ID)
);
END