USE [GA2]
GO

/****** Object:  Table [dbo].[SMC_SIMULACION_CLIENTE]    Script Date: 6/07/2021 7:30:15 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SMC_SIMULACION_CLIENTE](
	[SMC_ID] [uniqueidentifier] NOT NULL,
	[SLS_ID] [uniqueidentifier] NOT NULL,
	[SDP_ID] [uniqueidentifier] NOT NULL,
	[SMC_TIPO_VIVIENDA] [char](1) NOT NULL,
	[SMC_VALOR_VIVIENDA] [decimal](26, 6) NOT NULL,
	[SMC_TIPO_ALIVIO] [char](1) NOT NULL,
	[SMC_TIPO_ABONO] [char](1) NOT NULL,
	[SMC_NUMERO_DOCUMENTO] [varchar](15) NOT NULL,
	[SMC_VALOR_PRESTAMO] [decimal](26, 6) NOT NULL,
	[SMC_VALOR_TASA_EA] [decimal](20, 17) NOT NULL,
	[SMC_VALOR_TASA_MV] [decimal](20, 17) NOT NULL,
	[SMC_VALOR_TASA_MV_FRESH] [decimal](20, 17) NOT NULL,
	[SMC_VIVIENDA_VIS] [char](1) NOT NULL,
	[SMC_FECHA_SIMULACION] [datetime] NOT NULL,
	[SMC_USA_REC_ACUMULADO] [char](1) NOT NULL,
	[SMC_TOMA_SEGURO] [char](1) NOT NULL,
	[SMC_VALOR_PRESTAMO_LSG] [decimal](26, 6) NOT NULL,
	[SMC_NUMERO_PREAPROBADO] [bigint] NULL,
	[SMC_TOTAL_CUOTAS] [int] NULL,
	[SMC_FECHA_APROBACION] [datetime] NULL,
 CONSTRAINT [PK_SMC_SIMULACION_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[SMC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SMC_SIMULACION_CLIENTE] ADD  CONSTRAINT [DF_SMC_SIMULACION_CLIENTE_SMC_USA_REC_ACUMULADO]  DEFAULT ('N') FOR [SMC_USA_REC_ACUMULADO]
GO

ALTER TABLE [dbo].[SMC_SIMULACION_CLIENTE] ADD  CONSTRAINT [DF_SMC_SIMULACION_CLIENTE_SMC_TOMA_SEGURO]  DEFAULT ('N') FOR [SMC_TOMA_SEGURO]
GO

ALTER TABLE [dbo].[SMC_SIMULACION_CLIENTE] ADD  CONSTRAINT [DF_SMC_SIMULACION_CLIENTE_SMC_VALOR_PRESTAMO_LSG]  DEFAULT ((0)) FOR [SMC_VALOR_PRESTAMO_LSG]
GO


