USE [GA2]
GO

/****** Object:  Table [dbo].[ICO_INTEGRANTE_COMITE_CREDITO]    Script Date: 6/07/2021 9:09:16 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ICO_INTEGRANTE_COMITE_CREDITO](
	[ICO_ID] [int] IDENTITY(1,1) NOT NULL,
	[ICO_NOMBRE] [varchar](100) NOT NULL,
	[ICO_CARGO] [varchar](100) NOT NULL,
	[ICO_TIPO] [varchar](15) NOT NULL,
	[ICO_ESTADO] [bit] NOT NULL,
	[ICO_CREADO_POR] [uniqueidentifier] NOT NULL,
	[ICO_FECHA_CREACION] [datetime] NOT NULL,
	[ICO_ACTUALIZADO_POR] [uniqueidentifier] NULL,
	[ICO_FECHA_ACTUALIZA] [datetime] NULL,
 CONSTRAINT [PK_ICO_INTEGRANTE_COMITE_CREDITO] PRIMARY KEY CLUSTERED 
(
	[ICO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


