/*
Nombre: STI_SOLICITUD_INF_TEC_INM
Descripcion: Tabla solicitud informacion tec
Elaboro: Camilo Andres Yaya Poveda
Fecha: Mayo 7 de 2021
*/
IF OBJECT_ID('GA2.dbo.STI_SOLICITUD_INF_TEC_INM') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.STI_SOLICITUD_INF_TEC_INM;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.STI_SOLICITUD_INF_TEC_INM (
	STI_ID uniqueidentifier NOT NULL,
	SIT_ID uniqueidentifier NOT NULL,
	SOC_ID uniqueidentifier NOT NULL,
	STI_NUMERO_MATRICULA varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	STI_FECHA_MATRICULA date NOT NULL,
	STI_NUMERO_CHIP varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	STI_CEDULA_CATASTRAL varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	STI_CREADO_POR uniqueidentifier NOT NULL,
	STI_FECHA_CREACION datetime NOT NULL,
	STI_ACTUALIZADO_POR uniqueidentifier NOT NULL,
	STI_FECHA_ACTUALIZA datetime NOT NULL,
	CONSTRAINT PK_STI_SOLICITUD_INF_TEC_INM PRIMARY KEY (STI_ID),
	CONSTRAINT FK_STI_SOLICITUD_INF_TEC_INM_SOC_SOLICITUD_CREDITO FOREIGN KEY (SOC_ID) REFERENCES GA2.dbo.SOC_SOLICITUD_CREDITO(SOC_ID)
);
END