/*
Nombre: COLOR_GRILLA
Descripcion: Tabla COLOR_GRILLA
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/

IF OBJECT_ID('GA2.dbo.CLG_COLOR_GRILLA') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.CLG_COLOR_GRILLA;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.CLG_COLOR_GRILLA (
	CLG_ID int IDENTITY(1,1) NOT NULL,
	CLG_DESCRIPCION varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CLG_ESTILO_COLOR varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CLG_ESTADO int NOT NULL,
	CLG_CREADO_POR uniqueidentifier NOT NULL,
	CLG_FECHA_CREACION datetime NOT NULL,
	CLG_ACTUALIZADO_POR uniqueidentifier NULL,
	CLG_FECHA_ACTUALIZA datetime NULL,
	CONSTRAINT PK_CLG_COLOR_GRILLA PRIMARY KEY (CLG_ID)
);
END