/*
Nombre: FLUJO_TIPO_CREDITO
Descripcion: Tabla FLUJO_TIPO_CREDITO
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/

IF OBJECT_ID('GA2.dbo.FTC_FLUJO_TIPO_CREDITO') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.FTC_FLUJO_TIPO_CREDITO;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.FTC_FLUJO_TIPO_CREDITO (
	FTC_ID int IDENTITY(1,1) NOT NULL,
	FLU_ID int NOT NULL,
	TCR_ID int NOT NULL,
	FTC_ESTADO int NOT NULL,
	FTC_CREADO_POR uniqueidentifier NOT NULL,
	FTC_FECHA_CREACION datetime NOT NULL,
	FTC_MODIFICADO_POR uniqueidentifier NULL,
	FTC_FECHA_MODIFICACION datetime NULL,
	CONSTRAINT PK_FTC_FLUJO_TIPO_CREDITO PRIMARY KEY (FTC_ID)
);
END