USE [GA2]
GO

/****** Object:  Table [dbo].[CDD_CAUSAL_DESISTIMIENTO_DES]    Script Date: 6/07/2021 9:07:28 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CDD_CAUSAL_DESISTIMIENTO_DES](
	[CDD_ID] [int] IDENTITY(1,1) NOT NULL,
	[CDD_DESCRIPCION] [varchar](70) NOT NULL,
	[CDD_ESTADO] [int] NOT NULL,
	[CDD_CREADO_POR] [uniqueidentifier] NOT NULL,
	[CDD_FECHA_CREACION] [datetime] NOT NULL,
	[CDD_MODIFICADO_POR] [uniqueidentifier] NULL,
	[CDD_FECHA_MODIFICACION] [datetime] NULL,
 CONSTRAINT [PK_CDD_CAUSAL_DESISTIMIENTO_DES] PRIMARY KEY CLUSTERED 
(
	[CDD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


