/*
Nombre: ESTADO_ACTIVIDAD
Descripcion: Tabla ESTADO_ACTIVIDAD
Elaboro: Jorge Alberto Parrado Mariño
Fecha: Mayo 7 de 2021
*/
IF OBJECT_ID('GA2.dbo.ESA_ESTADO_ACTIVIDAD') IS NOT NULL
BEGIN
SELECT * FROM GA2.dbo.ESA_ESTADO_ACTIVIDAD;
END
ELSE
BEGIN
CREATE TABLE GA2.dbo.ESA_ESTADO_ACTIVIDAD (
	ESA_ID int IDENTITY(1,1) NOT NULL,
	ESA_DESCRIPCION varchar(70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ESA_ESTADO int NOT NULL,
	ESA_CREADO_POR uniqueidentifier NOT NULL,
	ESA_FECHA_CREACION datetime NOT NULL,
	ESA_MODIFICADO_POR uniqueidentifier NULL,
	ESA_FECHA_MODIFICACION datetime NULL,
	CONSTRAINT PK_ESA_ESTADO_ACTIVIDAD PRIMARY KEY (ESA_ID)
);
END