-- =============================================
--Author:		< Author,,Name >
--Create date: < Create Date,,>
--Description:	< Description,,>
-- =============================================
CREATE PROCEDURE[dbo].[ValidarNomina]
	-- Add the parameters for the stored procedure here
	@Json nvarchar(max)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

DECLARE @REGISTROSNOMINA TABLE (DIGITO_FUERZA INT, TIPO_IDENTIFICACION INT, IDENTIFICACION VARCHAR(MAX), CODIGO_MILITAR INT,
								PRIMER_NOMBRE VARCHAR(MAX), SEGUNDO_NOMBRE VARCHAR(MAX), PRIMER_APELLIDO VARCHAR(MAX),
									SEGUNDO_APELLIDO VARCHAR(MAX), GRADO INT, UNIDAD_OPERATIVA INT);

INSERT INTO @REGISTROSNOMINA
	SELECT CAST(DIGITO_FUERZA AS INT), CAST(TIPO_IDENTIFICACION AS INT), CAST(IDENTIFICACION AS INT), CODIGO_MILITAR,
									PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO,
									SEGUNDO_APELLIDO, GRADO, UNIDAD_OPERATIVA
	FROM OPENJSON (@Json)
	WITH(
	DIGITO_FUERZA INT,
	TIPO_IDENTIFICACION INT,
	IDENTIFICACION VARCHAR(MAX),
	CODIGO_MILITAR INT,
	PRIMER_NOMBRE VARCHAR(MAX),
	SEGUNDO_NOMBRE VARCHAR(MAX),
	PRIMER_APELLIDO VARCHAR(MAX),
	SEGUNDO_APELLIDO VARCHAR(MAX),
	GRADO INT,
	UNIDAD_OPERATIVA INT)

	SELECT r.*
	FROM @REGISTROSNOMINA r INNER JOIN[BUA].[dbo].CLI_CLIENTE c
	ON (c.CLI_IDENTIFICACION<> r.IDENTIFICACION)OR(c.TID_ID <> r.TIPO_IDENTIFICACION)OR(c.CLI_CODIGO_MILITAR <> r.CODIGO_MILITAR)
		OR(c.CLI_PRIMER_NOMBRE <> r.PRIMER_NOMBRE)OR(c.CLI_SEGUNDO_NOMBRE <> r.SEGUNDO_NOMBRE)OR(c.CLI_PRIMER_APELLIDO <> r.PRIMER_APELLIDO)
		OR(c.CLI_SEGUNDO_APELLIDO <> r.SEGUNDO_APELLIDO)OR(c.GRD_ID <> r.GRADO)OR(c.FRZ_ID <> r.DIGITO_FUERZA)

END
