IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = N'GA2AZURELOGIN')
BEGIN
	DROP USER GA2AZURELOGIN
	DROP LOGIN GA2AZURELOGIN
END

CREATE LOGIN GA2AZURELOGIN WITH PASSWORD = 'jghf_QWERWTY_3425676_vcx'
GO

IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'GA2AZURELOGIN')
BEGIN
    CREATE USER GA2AZURELOGIN FOR LOGIN GA2AZURELOGIN
    EXEC sp_addrolemember N'db_owner', N'GA2AZURELOGIN'
	GRANT SELECT,UPDATE,INSERT,DELETE,EXECUTE ON SCHEMA::dbo TO GA2AZURELOGIN;
END;
GO
